"""Write prospective method files, without generating any benchmark world."""
from pathlib import Path
import json
from world_generator import STUDY,CLASSES,derive,FAMILIES
P=Path(__file__).resolve().parent

def obj(p):return dict(type='object',properties=p,required=list(p),additionalProperties=False)
s=dict(type='string',minLength=1,maxLength=1500);identifier=dict(type='string',pattern='^z[0-9a-f]{16}$')
ids=dict(type='array',items=identifier,uniqueItems=True,maxItems=8)
mechanism=obj(dict(contract_evidence_id=identifier,cause_evidence_id=identifier,effect_evidence_id=identifier,decisive_evidence_id=identifier,decisive_field=dict(type="string",pattern="^/[a-z_]+$"),observed_value=dict(type=["string","number","boolean"]),required_value=dict(type=["string","number","boolean"]),description=s))
schema=obj(dict(classification={'enum':list(CLASSES)},affected_component_ids={**ids,'maxItems':1},evidence_ids={**ids,'minItems':1},observed=dict(type='array',items=s,maxItems=5),inferred=dict(type='array',items=s,maxItems=5),unknown=dict(type='array',items=s,maxItems=5),diagnostic_statement=s,causal_mechanism={'anyOf':[mechanism,{'type':'null'}]},strongest_alternative_explanation=s,falsifier=s))
schema['allOf']=[{'if':{'properties':{'classification':{'const':CLASSES[0]}}},'then':{'properties':{'affected_component_ids':{**ids,'minItems':1,'maxItems':1},'causal_mechanism':mechanism}}}]
def dump(n,v):(P/n).write_text(json.dumps(v,indent=2)+'\n')
def main():
 definitions=dict(zip(CLASSES,[
 'Available current evidence supports a specific active structural or mechanical defect and distinguishes it from materially plausible benign alternatives.',
 'The internally valid evidence is sufficient within the declared contract/input scope and supports no current defect. Unusual or undesirable behavior alone is insufficient.',
 'The evidence is internally valid but a current defect and a materially plausible benign explanation remain observationally indistinguishable.',
 'A defect is demonstrated for an older version, while supplied current mechanisms and observations show it is no longer active within the stated scope.',
 'The supplied evidence package contains incompatible immutable, version, capture or provenance facts and cannot support a valid operational diagnosis.']))
 system='You analyze an unfamiliar bounded software system. Machine facts are authoritative within their declared scope; contradictory evidence cannot be silently reconciled. UNKNOWN remains UNKNOWN. Distinguish observation, inference, and missing information. Use supplied implementation observations rather than simulating a policy already computed in the records. Do not invent hidden facts. No current diagnosis is required. Return one JSON object satisfying the supplied schema. Diagnose only: no solution, modification, experiment proposal, tools, or authority to change the system. Cite the governing contract and records establishing your conclusion. For a current defect, identify one responsible component and link the operative input/configuration record to its resulting observation using causal_mechanism; cite all witness IDs in evidence_ids. Also identify one decisive field as a JSON pointer relative to the data object of decisive_evidence_id and give its observed_value and the contract-required required_value. For a historical conclusion cite both version traces and deployment. Free prose does not override structured fields.'
 user='Classify this system at its declared current deployment. Use exactly one class according to the definitions below. Observations for other versions are not automatically current. Unusual outcomes can satisfy a contract. Return the raw diagnostic result, including a falsifier and strongest alternative, without proposing an intervention.\nDEFINITIONS:\n{definitions}\nSYSTEM_RECORDS:\n{case}'
 dump('diagnostic-schema.json',schema)
 dump('protocol.json',dict(study=STUDY,stage='ZERO_INFERENCE_METHOD_ONLY',ontology=definitions,system_prompt=system,user_prompt_template=user,case_distribution=dict(zip(CLASSES,[6,4,4,3,3])),semantic_units=20,label_maps=['A','B'],presentation_orders=[1,2],renderings=80,defect_families=list(FAMILIES),generator_seed_string=STUDY,seed_derivation='SHA256(UTF-8(seed_string + U+0000 + domain)); integer quantities use first 8 bytes big-endian modulo the declared bound; opaque IDs use first 16 hex digits; semantic IDs use first 16 hex digits. Model seed uses first 4 bytes masked with 0x7fffffff. No RNG/version-dependent random library.',model_seed_domain='model-seed',mandatory_gates=dict(semantic_classification_min=17,current_defect_classification_min=5,current_defect_localization_min=4,healthy_semantic_avoid_current=4,healthy_rendering_current_false_positives_max=0,historical_semantic_avoid_current=3,historical_rendering_current_false_positives_max=0,insufficient_classification_min=3,invalid_classification_min=3,counterfactual_pairs_min=5,representation_consistent_min=16,evidence_grounded_semantics_min=17,invented_ids_max=0),overall_taxonomy=['BLIND_DIAGNOSTIC_CAPABILITY_SUPPORTED_V0','BLIND_DIAGNOSTIC_CAPABILITY_NOT_ESTABLISHED_V0','INVALID_STUDY']))
 prior=P.parent/'agent-led-diagnosis-verified-introspection-v0'
 cfg=json.loads((prior/'analysis-configuration.json').read_text());cfg.pop('max_analysis_calls');cfg.pop('endpoint');cfg.update(seed=int.from_bytes(derive(STUDY,'model-seed')[:4],'big')&0x7fffffff,max_tokens=2048,future_analysis_calls=80,calls_authorized_now=0,tools=[],filesystem_access=False,web_access=False,isolated_server_host='127.0.0.1',parallel=1,context_reset_per_call=True,kv_cache_reuse=False,planned_runtime_flags=['--ctx-size','16384','--parallel','1','--jinja','--n-gpu-layers','999','--flash-attn','on','--reasoning','on','--reasoning-format','deepseek','--reasoning-budget','512'])
 dump('model-runtime.json',dict(configuration=cfg,artifact_provenance=dict(parent_study='agent-led-diagnosis-verified-introspection-v0',parent_verification=json.loads((prior/'runtime-verification.json').read_text()),verified_again_for_this_study=False),verification_note='Exact hashes inherited from the verified parent; recheck bytes before any separately approved inference. No server is started in this phase.'))
if __name__=='__main__':main()
