"""Render descriptive tables from frozen scores only; zero inference."""
import json
from pathlib import Path
P=Path(__file__).resolve().parent
def render(s):
 m=s['matched_comparison'];q=m['reduction']['qwen'];c=s['reduction'];out=['# Frozen Cross-Model Epistemic Comparator v0','',s['registered_interpretation']['pattern'],'','Comparator: mistralai/Ministral-3-14B-Reasoning-2512, official Q8_0 GGUF. Source publication: 2cfcf8097c99d13df2156dde47409af0f65cb42a. See model-runtime.json for exact artifact/runtime hashes, method.md for preregistration, and completion.json for all freeze/publication references.','',f"Scheduled 112; attempted {s['attempted']}; completed {s['completed']}. Comparator schema-valid: primitives {sum(x['schema_valid'] for x in s['primitives'].values())}/56; reduction {c['schema_valid']}/56. Qwen's immutable reference has 112/112 schema-valid.",'','Q = published Qwen; C = comparator. All endpoint/pair comparisons are descriptive, with correlated states/pairs. No pooled intelligence score or causal percentages.']
 def table(headers,rows):
  out.extend(['','| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |'])
  for row in rows:out.append('| '+' | '.join(str(x).replace('|','\\|').replace('\n',' ') for x in row)+' |')
 def sel(x):return 'INVALID' if x is None else '`'+json.dumps(x,sort_keys=True,separators=(',',':'))+'`'
 def ids(xs):return ', '.join(xs) if xs else 'none'
 out.extend(['','## Primitive overview'])
 table(['Primitive','Q endpoints','C endpoints','Q pairs','C pairs','C schema','C gate'],[[f,'8/8',f"{x['correct']}/8",'4/4',f"{x['pair_passes']}/4",f"{x['schema_valid']}/8",x['gate']] for f,x in s['primitives'].items()])
 for f,x in s['primitives'].items():
  out.extend(['',f'## {f}'])
  if 'fields' in x:out.append(f"Identity fields: same_referent {x['fields']['same_referent']}/8; equal_value {x['fields']['equal_value']}/8; joint exact {x['correct']}/8.")
  table(['State','Gold','Q selected','C selected','Q correct','C correct','C schema'],[[r['world_id'],sel(r['gold']),sel(r['qwen_selected']),sel(r['comparator_selected']),r['qwen_correct'],r['comparator_correct'],r['comparator_schema_valid']] for r in m['tasks'] if r['family']==f and r['arm']=='P'])
  table(['Pair','Gold transition A → B','Q transition','C transition','Q pass','C pass'],[[r['pair_id'],' → '.join(sel(v) for v in r['comparator']['P_gold_transition']),' → '.join(sel(v) for v in r['qwen']['P_selected_transition']),' → '.join(sel(v) for v in r['comparator']['P_selected_transition']),r['qwen']['P_pair_pass'],r['comparator']['P_pair_pass']] for r in m['pairs'] if r['family']==f])
  info=m['primitives'][f];out.extend(['',f"Endpoint answer disagreements: {ids(info['endpoint_answer_disagreements'])}. Endpoint correctness disagreements: {ids(info['endpoint_correctness_disagreements'])}. Pair pass disagreements: {ids(info['pair_pass_disagreements'])}. Pair transition disagreements: {ids(info['pair_transition_disagreements'])}.",'','Comparator confusion counts:','```json',json.dumps({k:v for k,v in x.items() if 'confusion' in k},indent=2),'```'])
 out.extend(['','## Five-class reduction'])
 table(['Metric','Qwen','Comparator'],[['Correct /56',q['correct'],c['correct']],['Gate',q['gate'],c['gate']],['Schema /56',q['schema_valid'],c['schema_valid']],['Exact pairs /28',q['exact_pair_passes'],c['exact_pair_passes']],['Diagnostic flip /19',q['flip_pair_passes'],c['flip_pair_passes']],['Stable retention /9',q['stable_pair_passes'],c['stable_pair_passes']]])
 table(['Class','Q correct','C correct','Frozen floor','C minus Q'],[[cl,f"{q['per_class'][cl]['correct']}/{v['denominator']}",f"{v['correct']}/{v['denominator']}",v['minimum'],m['reduction']['class_correct_differences'][cl]] for cl,v in c['per_class'].items()])
 classes=list(c['confusion']);short=['D','N','U','H','X'];out.extend(['','Confusion rows are gold, columns selected. D=current defect; N=no supported diagnosis; U=insufficient; H=historical; X=invalid/contradictory; I=invalid output.'])
 table(['Gold']+['Q '+x for x in short+['I']]+['C '+x for x in short+['I']],[[short[i]]+[mat[cl][k] for mat in (q['confusion'],c['confusion']) for k in classes+['INVALID_OUTPUT']] for i,cl in enumerate(classes)])
 table(['Aligned family','Q reduction /8','C reduction /8','Q exact /4','C exact /4','Q flips','C flips','Q stable','C stable'],[[f,sum(r['qwen']['R_correct'] for r in m['states'] if r['family']==f),x['R_correct'],sum(r['qwen']['R_exact_pair_pass'] for r in m['pairs'] if r['family']==f),x['R_exact_pair_passes'],sum(bool(r['qwen']['R_flip_pass']) for r in m['pairs'] if r['family']==f),f"{x['R_flip_pair_passes']}/{x['R_flip_pairs']}" if x['R_flip_pairs'] else 'N/A',sum(bool(r['qwen']['R_stable_class_retention_pass']) for r in m['pairs'] if r['family']==f),f"{x['R_stable_pair_passes']}/{x['R_stable_pairs']}" if x['R_stable_pairs'] else 'N/A'] for f,x in s['family_comparisons'].items()])
 out.extend(['','## All reduction endpoints and state joint outcomes'])
 table(['State','Family','Gold R','Q P','Q R','C P','C R','Q selected R','C selected R'],[[r['world_id'],r['family'],sel(r['comparator']['R_gold']),r['qwen']['P_correct'],r['qwen']['R_correct'],r['comparator']['P_correct'],r['comparator']['R_correct'],sel(r['qwen']['R_selected']),sel(r['comparator']['R_selected'])] for r in m['states']])
 table(['State category','Count','Exact members'],[[k,v['count'],ids(v['members'])] for k,v in m['state_categories'].items()])
 table(['Within-model category','Q count','C count'],[[k,m['qwen_joint'][k]['count'],m['comparator_joint'][k]['count']] for k in m['qwen_joint']])
 out.extend(['','## All 28 reduction matched pairs'])
 table(['Pair','Family','Gold changes','Q A → B','C A → B','Q exact pass','C exact pass','Q flip/stable','C flip/stable'],[[r['pair_id'],r['family'],r['comparator']['diagnostic_gold_changes'],' → '.join(sel(x) for x in r['qwen']['R_selected_transition']),' → '.join(sel(x) for x in r['comparator']['R_selected_transition']),r['qwen']['R_exact_pair_pass'],r['comparator']['R_exact_pair_pass'],str(r['qwen']['R_flip_pass'])+'/'+str(r['qwen']['R_stable_class_retention_pass']),str(r['comparator']['R_flip_pass'])+'/'+str(r['comparator']['R_stable_class_retention_pass'])] for r in m['pairs']])
 out.extend(['','## Evidence-sufficiency subset'])
 es=m['evidence_sufficiency'];table(['Measure','Q','C'],[[key,es['qwen'][key],es['comparator'][key]] for key in ('P_correct','P_pair_passes','R_correct','R_exact_pair_passes')])
 table(['State','Q P selected','C P selected','Gold R','Q R selected','C R selected'],[[r['world_id'],sel(r['qwen']['P_selected']),sel(r['comparator']['P_selected']),sel(r['comparator']['R_gold']),sel(r['qwen']['R_selected']),sel(r['comparator']['R_selected'])] for r in es['states']])
 table(['Pair','Q primitive flip','C primitive flip','Q reduction exact','C reduction exact'],[[r['pair_id'],r['qwen']['P_pair_pass'],r['comparator']['P_pair_pass'],r['qwen']['R_exact_pair_pass'],r['comparator']['R_exact_pair_pass']] for r in es['pairs']])
 out.extend(['','## Registered interpretation and limits','',json.dumps(s['registered_interpretation'],indent=2),'',f"Shared reduction-error states: {ids(m['reduction']['shared_error_states'])}.",'','The comparison is specific to the frozen messages, native model interfaces, quantizations and runtime budgets. Native Ministral reasoning is optional and no reasoning prompt was added to scientific inputs. Separate primitive calls do not establish correct primitive computation inside reduction calls. Similar observed errors do not identify a causal mechanism.','', 'Qwen model capability: immutable published reference. Comparator capability: measured here. Deterministic software capability: verification, transport, hashing and scoring. Combined-system capability: NOT TESTED. No primitive output is passed into reduction, no deterministic helper chooses diagnoses, and no Horus/Memory/policy/weights change, training, promotion or self-improvement occurs.','', 'No result here tests a Horus intervention or automatically authorizes one. No further study is started.'])
 return '\n'.join(out)+'\n'
if __name__=='__main__':
 s=json.loads((P/'scores.json').read_bytes());assert s['status']=='MINISTRAL_CROSS_MODEL_COMPARATOR_COMPLETE_V0'
 with (P/'report.md').open('x') as f:f.write(render(s))
