"""Deterministic, source-bound representation of the existing published architecture."""
from pathlib import Path
from hashlib import sha256
import ast,json,itertools
P=Path(__file__).resolve().parent;R=P.parents[1]
BASE='ba698e948e2ae27427bac1e9f772cf6c8b485de8';ACTIVE='69947aa243a69e7ae26db534727a7122922d978d'
def write(name,v):(P/name).write_text(json.dumps(v,indent=2)+'\n')
def read(path):return (R/path).read_text()
def source(id,path,symbols):
 text=read(path);tree=ast.parse(text);available={n.name for n in ast.walk(tree) if isinstance(n,(ast.ClassDef,ast.FunctionDef))}
 assert all(s in available for s in symbols),(id,symbols)
 return dict(source_id=id,path=path,sha256=sha256(text.encode()).hexdigest(),symbols=symbols)
index=[source(*x) for x in [
 ('SRC-SELECTOR','grounded_agent/empirical_policy.py',['integrated_decide']),
 ('SRC-ADAPTER','grounded_agent/empirical_adapter.py',['authenticated_projection','recommendation','IntegrationInvariantError']),
 ('SRC-ROLLBACK','grounded_agent/policy.py',['promoted_decide','previous_incumbent_decide']),
 ('SRC-ROUTING','experiments/grounded_authority_autonomous_agent_v0/protocol.py',['known_value','select_route']),
 ('SRC-S','experiments/grounded_stagnation_escape_evaluation_v0/candidate.py',['qualifying_suffix','escape_choice']),
 ('SRC-E','experiments/empirical_evidence_acquisition_proposal_v0/candidate.py',['evaluate','empirical_component']),
 ('SRC-DETERMINISTIC','grounded_state/deterministic.py',['fold']),
 ('SRC-EMPIRICAL','grounded_state/empirical.py',['fold']),
 ('SRC-GROUNDED-CORE','grounded_state/core.py',['AuthenticatedMemory','derive_relation_state','assess_relation']),
 ('SRC-MEMORY','experiments/modern_memory_vs_horus_v0/storage.py',['record','reconcile']),
 ('SRC-REPLAY','horus/live.py',['SessionStore','_read_stream','_validate_events','imported_history']),
 ('SRC-EXECUTION','experiments/grounded_stagnation_escape_evaluation_v0/worker.py',['execute']),
 ('SRC-AUTHORIZATION','experiments/realized_event_grounding_v0/framework.py',['_check','submit_package']),
 ('SRC-ORDINARY','experiments/grounded_stagnation_escape_promotion_controlled_v0/worker.py',['canonical_action_decision','frozen_decide','context']),
 ('SRC-TYPE-MAP','experiments/grounded_autonomous_agent_v0/protocol.py',['relation_type'])]]
for id,path in [('SRC-ENTRY','grounded_agent/__init__.py'),('SRC-PROMOTION','research/empirical-evidence-acquisition-promotion-v0/promotion-record.json'),('SRC-MODEL-STATUS','research/qwen3-r128-autonomous-grounded-agent-v0/result.md')]:
 index.append(dict(source_id=id,path=path,sha256=sha256((R/path).read_bytes()).hexdigest(),symbols=[]))
assert 'decide = integrated_decide' in read('grounded_agent/__init__.py')
assert sha256((R/'experiments/empirical_evidence_acquisition_proposal_v0/candidate.py').read_bytes()).hexdigest()=='fcef478a02beb69a1d29988c5ce12929ad2ba077591131e0dcd114e7ccab99b4'
assert sha256((R/'experiments/grounded_stagnation_escape_evaluation_v0/candidate.py').read_bytes()).hexdigest()=='2293c46be58684f6dcf903b82dff7d29bc9fdef69790b4c22e154c750c8a5b92'
selector=read('grounded_agent/empirical_policy.py')
assert selector.index("context['route']['route'] == 'MECHANICAL'")<selector.index("s_action is not None and e['eligible']")<selector.index('if s_action is not None:')<selector.index("if not e['eligible']:")
G='GROUNDED_MECHANICAL_AUTHORITY';S='S_BOUNDED_STAGNATION_ESCAPE';E='E_EMPIRICAL_EVIDENCE_ACQUISITION';M='ORDINARY_MODEL_ROUTE'
components=[]
def component(id,status,role,ids,select=False,execute=False,memory=False,auth=False,derive=False,model=False,scope='',inputs=(),outputs=(),facts=None):
 fields=dict(component_id=id,status=status,role=role,can_select_action=select,can_execute_world=execute,can_write_memory=memory,can_authenticate_receipt=auth,can_modify_grounded_state=derive,uses_model_call_when_triggered=model,scope_summary=scope,inputs=list(inputs),outputs=list(outputs),facts=facts or {})
 components.append({**fields,'source_ids':ids,'field_source_ids':{k:ids for k in fields}})
component('ACTIVE_SELECTOR','ACTIVE','DECISION_ORCHESTRATOR',['SRC-ENTRY','SRC-SELECTOR'],select=True,model=True,scope='Dispatches authenticated context to existing mechanical authority, S, E, or ordinary route; journals choices but does not execute or write grounded Memory.',inputs=['authenticated context','admissible actions'],outputs=['selected action tuple or fail-closed error'],facts=dict(callable='grounded_agent.empirical_policy.integrated_decide',entry_point='grounded_agent.decide'))
component(G,'ACTIVE','GROUNDED_MECHANICAL_SELECTION',['SRC-ROUTING','SRC-SELECTOR'],select=True,scope='Uses authenticated deterministic established values to resolve an established +1 ceiling, or the best value when all actions are established. Distinct from S.',inputs=['grounded assessments'],outputs=['mechanical action or unresolved route'],facts=dict(is_S=False,precedes=[S,E,M],established_ceiling=1,all_established_resolution=True))
component(S,'PROMOTED_ACTIVE','DETERMINISTIC_STAGNATION_ESCAPE',['SRC-S','SRC-SELECTOR','SRC-PROMOTION'],select=True,scope='Frozen deterministic established-zero repeated fallback escape; chooses one canonical truly unseen alternative. Not grounded mechanical authority and not E.',inputs=['authenticated signed decisions','grounded deterministic assessments'],outputs=['one unseen target or no trigger'],facts=dict(threshold=3,repeated_relation_type='DETERMINISTIC',required_kind='ESTABLISHED',required_consequence=0,requires_same_state_action_self_loop=True,requires_safe_fallback_decisions=True,requires_true_unseen=True,excluded_established_ceiling=1,canonical_action_order=['ADVANCE','HOLD','RETREAT'],reset='RECONSTRUCT_FROM_AUTHENTICATED_SUFFIX',can_create_receipt=False))
component(E,'PROMOTED_ACTIVE','EMPIRICAL_EVIDENCE_ACQUISITION',['SRC-E','SRC-ADAPTER','SRC-SELECTOR','SRC-PROMOTION'],select=True,scope='Frozen empirical deterioration plus missing-evidence rule. Selects one canonical unseen relation after qualifying self-loop suffix. Distinct from S.',inputs=['verified chronological history','grounded empirical assessments','admissible actions'],outputs=['one unseen target or no trigger'],facts=dict(window=4,recent_sum_max=0,cumulative_sum_max=0,allowed_kinds=['EMPIRICALLY_STABLE','VARIABLE_RELATION'],excluded_kind='POSSIBLE_REGIME_CHANGE',requires_same_state_action_self_loop=True,requires_true_unseen=True,excluded_established_ceiling=1,canonical_action_order=['ADVANCE','HOLD','RETREAT'],reset='RECONSTRUCT_FROM_AUTHENTICATED_SUFFIX',can_create_receipt=False))
component(M,'ACTIVE_INCUMBENT','ADMISSIBLE_MODEL_SELECTION',['SRC-ORDINARY','SRC-ROUTING','SRC-MODEL-STATUS'],select=True,model=True,scope='Existing ordinary incumbent model/mixed path chooses only within admissible actions when mechanical/S/E do not resolve. It cannot rewrite authenticated grounded state.',inputs=['goal','admissible actions','grounded assessments','bounded history'],outputs=['validated selected action or error'],facts=dict(model_incumbent='DOLPHIN',Qwen_action_substitution='NOT_PROMOTED',position='AFTER_MECHANICAL_S_E',can_overwrite_authenticated_experience=False))
component('GROUNDED_DETERMINISTIC_STATE','ACTIVE','DETERMINISTIC_EVIDENCE_DERIVATION',['SRC-DETERMINISTIC','SRC-GROUNDED-CORE'],derive=True,scope='Derives deterministic relation state from authenticated exact-relation observations; exposes contradiction as unresolved.',inputs=['authenticated exact-relation Memory rows'],outputs=['UNSEEN','ESTABLISHED','UNRESOLVED_CHANGE'])
component('GROUNDED_EMPIRICAL_STATE','ACTIVE','EMPIRICAL_EVIDENCE_DERIVATION',['SRC-EMPIRICAL','SRC-GROUNDED-CORE','SRC-TYPE-MAP'],derive=True,scope='Derives empirical observations/windows/classifications from authenticated rows and explicitly configured relation type; no automatic type discovery.',inputs=['authenticated exact-relation Memory rows','explicit relation type'],outputs=['UNSEEN','EMPIRICALLY_STABLE','VARIABLE_RELATION','POSSIBLE_REGIME_CHANGE'])
component('AUTHENTICATED_MEMORY','ACTIVE','AUTHORIZED_DURABLE_EVIDENCE_STORE',['SRC-MEMORY','SRC-REPLAY','SRC-GROUNDED-CORE'],memory=True,scope='Owns durable admission of already authorized receipts and signed-history reconciliation; verifies stored provenance, but does not originate protected receipt authorization.',inputs=['current authorized receipt event','signed checkpoint and streams'],outputs=['durable exact-relation rows','verified provenance or error'],facts=dict(authorization_required_before_admission=True,can_verify_stored_signed_provenance=True,can_originate_receipt=False))
component('PROTECTED_EXECUTION','ACTIVE','PROTECTED_WORLD_AND_AUTHORIZATION',['SRC-EXECUTION','SRC-AUTHORIZATION'],execute=True,memory=True,auth=True,scope='Existing protected worker executes the selected action, preserves its original receipt, runs Measure/authorization and admits authorized evidence to core/durable Memory. It does not choose the policy action.',inputs=['frozen selected action'],outputs=['original receipt','authorization result','authorized Memory admission'],facts=dict(can_create_original_receipt=True,unauthorized_memory_admission=False))
component('ROLLBACK_SELECTOR','AVAILABLE_ROLLBACK','PRE_E_AUTHORITY_PLUS_S_SELECTOR',['SRC-ROLLBACK','SRC-PROMOTION'],select=True,model=True,scope='Callable exact pre-E grounded authority plus S selector; ordinary model fallback remains. Not the older authority-only previous_incumbent_decide.',inputs=['same authenticated incumbent context'],outputs=['pre-E selected action tuple'],facts=dict(callable='grounded_agent.policy.promoted_decide',includes_E=False,includes_S=True))
manifest=dict(snapshot_commit=ACTIVE,publication_parent=BASE,definition='Current factual interface only; no diagnosis, future candidate or hidden outcome.',field_semantics=dict(can_select_action='Can choose/dispatch the policy action, excluding merely executing an already frozen action.',can_write_memory='Can admit observations to core or durable grounded Memory; choice/checkpoint journals alone do not count.',can_authenticate_receipt='Can grant original protected receipt/package authorization, not merely verify stored provenance.',can_modify_grounded_state='Owns evidence-derived state computation; never permission to invent evidence or retune the fold.',uses_model_call_when_triggered='True if a valid invocation may make/delegate a model call. For dispatchers this is conditional, not every invocation. False means no inference in that component.'),components=components)
graph=dict(source_ids=['SRC-ENTRY','SRC-SELECTOR','SRC-ADAPTER','SRC-ROUTING'],precondition='AUTHENTICATED_CONTEXT_VALIDATED_BEFORE_ROUTING',ordered_decision_layers=[G,S,E,M],model_route_position='AFTER_MECHANICAL_S_E',rollback_component='ROLLBACK_SELECTOR',distinctions=[dict(a=G,b=S,relationship='DISTINCT_COMPONENTS',evidence_ids=['SRC-ROUTING','SRC-S','SRC-SELECTOR']),dict(a=S,b=E,relationship='DISTINCT_COMPONENTS',evidence_ids=['SRC-S','SRC-E'])],failure_behavior=[dict(condition='SIMULTANEOUS_S_AND_E_ELIGIBILITY',behavior='INTEGRATION_INVARIANT_ERROR',action_emitted=False,model_called=False,evidence_ids=['SRC-SELECTOR']),dict(condition='MALFORMED_AUTHENTICATED_E_HISTORY',behavior='FAIL_CLOSED',action_emitted=False,model_called=False,evidence_ids=['SRC-ADAPTER','SRC-SELECTOR'])],mutual_exclusivity='Valid S repeats deterministic established-zero; valid E repeats an explicitly empirical relation. An inconsistent joint report aborts rather than choosing a winner.')
registry=dict(source_ids=['SRC-ENTRY','SRC-PROMOTION','SRC-MODEL-STATUS'],S='PROMOTED_ACTIVE',E='PROMOTED_ACTIVE',Qwen_action_model='NOT_PROMOTED',Dolphin='ACTIVE_HISTORICAL_INCUMBENT_REFERENCE',study_Qwen_authority='FACTUAL_ANALYSIS_ONLY',diagnosis_authorized=False,proposal_authorized=False)
write('architecture-manifest.json',manifest);write('authority-graph.json',graph);write('source-index.json',dict(snapshot_commit=ACTIVE,sources=index));write('current-status-registry.json',registry)
# Pure synthetic interface descriptions, no receipts/Memory objects/worlds.
cases=[]
def add(id,context,owner,model=False,kind='MECHANICAL_SELECTION',failure=None):
 cases.append(dict(case_id=id,synthetic_context=context,expected=dict(owning_component=owner,model_called=model,action_authority_type=kind,failure_mode_if_any=failure),expected_action_emitted=failure is None))
add('T1',dict(authenticated_projection_valid=True,assessments=[dict(action='RETREAT',relation_type='DETERMINISTIC',kind='ESTABLISHED',consequence=1),dict(action='ADVANCE',kind='UNSEEN'),dict(action='HOLD',kind='UNSEEN')]),G)
for i,order in enumerate(itertools.permutations(['ADVANCE','HOLD','RETREAT'])):
 repeated=['ADVANCE','HOLD','RETREAT'][i%3];target=next(a for a in ['ADVANCE','HOLD','RETREAT'] if a!=repeated)
 add('T2'+chr(97+i),dict(authenticated_projection_valid=True,current_state=0,display_action_order=list(order),repeated_action=repeated,repeated_relation_type='DETERMINISTIC',repeated_kind='ESTABLISHED',repeated_consequence=0,consecutive_safe_fallback_self_loop_count=3,prior_choice_source='SAFE_GROUNDED_FALLBACK',prior_policy_route='MODEL',prior_parse_status='VALID',unseen_alternatives=[a for a in order if a!=repeated],established_plus_one_available=False),S,kind='BOUNDED_DETERMINISTIC_ESCAPE')
 # Keep active empirical typing HOLD in states 1/2; vary unseen target and all display permutations.
 add('T3'+chr(97+i),dict(authenticated_projection_valid=True,current_state=1+i%2,display_action_order=list(order),repeated_action='HOLD',repeated_relation_type='EMPIRICAL',repeated_kind='EMPIRICALLY_STABLE' if i%2==0 else 'VARIABLE_RELATION',same_relation_self_loop_suffix_count=4,recent_consequences=[-1]*4 if i%2==0 else [-1,0,-1,0],recent_sum=-4 if i%2==0 else -2,cumulative_sum=-4 if i%2==0 else -2,unseen_alternatives=['ADVANCE','RETREAT'] if i%2==0 else ['RETREAT'],other_observed_alternative=None if i%2==0 else dict(action='ADVANCE',kind='ESTABLISHED',relation_type='DETERMINISTIC',consequence=0),established_plus_one_available=False,possible_change=None),E,kind='BOUNDED_EMPIRICAL_ACQUISITION')
add('T4',dict(authenticated_projection_valid=True,mechanical_resolvable=False,S_eligible=False,E_eligible=False,uncertain_kind='UNRESOLVED_CHANGE',admissible_actions=['HOLD','RETREAT']),M,True,'MODEL_SELECTION')
add('T5',dict(authenticated_projection_valid=True,mechanical_resolvable=False,S_eligible=True,E_eligible=True,description='Intentionally inconsistent adapter report'), 'INTEGRATION_INVARIANT_ERROR',kind='NO_ACTION',failure='INTEGRATION_INVARIANT_ERROR')
add('T6',dict(authenticated_projection_valid=False,defect='Missing authenticated history sequence; do not infer missing receipts',mechanical_resolvable=False),'FAIL_CLOSED',kind='NO_ACTION',failure='FAIL_CLOSED')
for id,recent,cumulative,kind in [('T7',1,-1,'VARIABLE_RELATION'),('T8',-1,1,'VARIABLE_RELATION'),('T9',-4,-2,'POSSIBLE_REGIME_CHANGE')]:
 add(id,dict(authenticated_projection_valid=True,current_state=1,mechanical_resolvable=False,repeated_action='HOLD',repeated_relation_type='EMPIRICAL',repeated_kind=kind,same_relation_self_loop_suffix_count=6,recent_sum=recent,cumulative_sum=cumulative,unseen_alternatives=['RETREAT'],established_plus_one_available=False,S_eligible=False),M,True,'MODEL_SELECTION')
add('T10',dict(authenticated_projection_valid=True,assessments=[dict(action=a,relation_type='DETERMINISTIC',kind='ESTABLISHED',consequence=v) for a,v in [('ADVANCE',-1),('HOLD',0),('RETREAT',-1)]],unseen_alternatives=[]),G)
write('routing-cases.json',dict(mode='SYNTHETIC_READ_ONLY_DESCRIPTIONS',no_simulator=True,no_Memory=True,no_receipts=True,cases=cases))
write('interface-build-audit.json',dict(status='PASS',sources=len(index),components=len(components),cases=len(cases),source_bound_declarative_facts=True,ast_symbols_validated=True,selector_precedence_source_assertions_pass=True,frozen_S_E_hashes_pass=True,manifest_fact_provenance='Every component field has field_source_ids; graph/registry fields inherit source_ids. Values describe current component responsibility, not proposed authority.'))
print('Built',len(components),'components and',len(cases),'registered synthetic cases')
if __name__=='__main__':pass
