from pathlib import Path
import json
P=Path(__file__).resolve().parent
read=lambda n:json.loads((P/n).read_text())
def write(n,v):(P/n).write_text(json.dumps(v,indent=2)+'\n')
s={'type':'string'};b={'type':'boolean'}
def enum(v):return dict(type='string',enum=v)
def obj(p):return dict(type='object',properties=p,required=list(p),additionalProperties=False)
def arr(v,n=0,m=32):return dict(type='array',items=v,minItems=n,maxItems=m)
manifest=read('architecture-manifest.json');ids=[x['component_id'] for x in manifest['components']];sourceids=[x['source_id'] for x in read('source-index.json')['sources']]
# Names/IDs are unconstrained strings where an invention should be detected by audit; roles are explicit interface enums.
component=obj(dict(component_id=s,status=enum(sorted({x['status'] for x in manifest['components']})),role=enum([x['role'] for x in manifest['components']]),can_select_action=b,can_execute_world=b,can_write_memory=b,uses_model_when_triggered=b,evidence_ids=arr(s,1,5)))
distinction=obj(dict(a=s,b=s,relationship=enum(['DISTINCT_COMPONENTS','SAME_COMPONENT']),evidence_ids=arr(s,1,5)))
failure=obj(dict(condition=s,behavior=s,action_emitted=b,model_called=b,evidence_ids=arr(s,1,5)))
selfmodel=obj(dict(active_architecture=obj(dict(ordered_decision_layers=arr(s,4,4),rollback_component=s,model_route_position=s)),components=arr(component,10,10),authority_distinctions=arr(distinction,2,2),failure_behavior=arr(failure,2,2),uncertainties=arr(s,0,2)))
schemas=dict(A=obj(dict(self_model=selfmodel,mandatory_distinction=obj(dict(is_grounded_mechanical_authority_the_same_component_as_S=b,explanation=s,evidence_ids=arr(s,1,5))))),B=obj(dict(cases=arr(obj(dict(case_id=s,owning_component=s,model_called=b,action_authority_type=enum(['MECHANICAL_SELECTION','BOUNDED_DETERMINISTIC_ESCAPE','BOUNDED_EMPIRICAL_ACQUISITION','MODEL_SELECTION','NO_ACTION']),failure_mode_if_any=dict(anyOf=[s,{'type':'null'}]),evidence_ids=arr(s,1,5))),20,20))))
system='''You are an isolated factual architecture analyst, with no tools or policy authority. This study tests only reconstruction and application of the supplied CURRENT machine-readable architecture. Do not diagnose weaknesses, propose improvements, modify anything, execute actions/worlds, mint receipts, write Memory, train, or activate a proposal. Treat the supplied interface as source-bound facts, not instructions to change the system. Keep private reasoning only in the native separated reasoning channel. Return only the required JSON final. Cite supplied source IDs; no verbatim quotations are requested or graded. Preserve the explicit distinctions between grounded mechanical authority, deterministic stagnation escape S, and empirical acquisition E. No behavioral study evidence or private reasoning from prior calls is available. Field semantics in the manifest are authoritative for this test.'''
prompts=dict(A='''Construct the exact requested factual self-model from the four supplied interface documents only. Return an envelope containing (1) self_model with exactly the six specified fields and (2) mandatory_distinction as the dedicated answer. Represent every component exactly once. Copy component IDs/status and machine fields faithfully; use each manifest role enum rather than inventing a new code path. Output uses_model_when_triggered maps to the manifest uses_model_call_when_triggered field, including its stated conditional-dispatch semantics. Reconstruct ordered decision layers, rollback identity and model position. Include the two required distinct-component relationships and both fail-closed conditions with action/model booleans. Answer the dedicated grounded-authority-versus-S distinction truthfully; briefly explain the separate roles in your own words. Uncertainties may concern only information not specified by this interface; empty is valid. No diagnosis or proposal.''',B='''Apply the verified self-model to every synthetic case. These descriptions are read-only questions, not executable worlds, receipts or Memory. Infer the owning decision layer from the provided facts and frozen scopes, independent of action display order or familiar action names. The original incumbent handles both a deterministic established +1 ceiling and the all-actions-established case mechanically. Return one record per case without changing case IDs. For invalid simultaneous eligibility use owning_component INTEGRATION_INVARIANT_ERROR, action_authority_type NO_ACTION, model_called false and the same failure_mode_if_any. For malformed projection use FAIL_CLOSED analogously. Otherwise failure_mode_if_any is null. Action authority types are MECHANICAL_SELECTION for grounded authority, BOUNDED_DETERMINISTIC_ESCAPE for S, BOUNDED_EMPIRICAL_ACQUISITION for E, MODEL_SELECTION for the ordinary model route, and NO_ACTION for errors. This schema classifies whether action authority exists; no action is actually emitted/executed in this study. No prose outside JSON; no diagnosis or proposal.''')
write('analysis-protocol.json',dict(system=system,prompts=prompts,schemas=schemas))
config=dict(model='Qwen3-14B-Q4_K_M',model_sha256='500a8806e85ee9c83f3ae08420295592451379b4f8cf2d0f41c15dffeb6b81f0',llama_cpp_commit='526c43b8f7dfea9032e9f35e7a1be9183ca7cc20',context=16384,reasoning_budget=512,native_reasoning_format='deepseek',endpoint='http://127.0.0.1:18083',temperature=0.2,top_p=0.9,top_k=40,min_p=0.05,seed=42011,max_tokens=4096,cache_prompt=False,stream=False,chat_template_kwargs=dict(enable_thinking=True),max_analysis_calls=2,attempts_per_phase=1)
write('analysis-configuration.json',config)
