import sys,json,subprocess
from pathlib import Path
P=Path(__file__).resolve().parents[1];R=P.parents[1];sys.path.insert(0,str(P))
from data import dump,rows

def load(n):return json.loads((P/n).read_bytes())
def commit_for(name):return subprocess.check_output(['git','log','-1','--format=%H','--',str((P/name).relative_to(R))],cwd=R,text=True).strip()
def rate(x,arm):return f"{x[arm+'_correct']}/{x['n']} ({100*x[arm+'_accuracy']:.2f}%)"
def table(comp,old,new):
 out=[f'| Metric | {old} | {new} | Change |','|---|---:|---:|---:|']
 for key in ['joint','current_violation','prior_violation','schema','targeted']:
  x=comp[key];out.append(f"| {key} | {rate(x,'incumbent')} | {rate(x,'candidate')} | {x['gain_pp']:+.2f} pp |")
 return '\n'.join(out)
def regression(reg):
 out=['| Family | Metric | Incumbent | Candidate | Change |','|---|---|---:|---:|---:|']
 for name,x in reg.items():out.append(f"| {name} | {x['metric']} | {rate(x,'incumbent')} | {rate(x,'candidate')} | {x['gain_pp']:+.2f} pp |")
 return '\n'.join(out)
results={str(i):load(f'cycle{i}-results.json') for i in [1,2] if (P/f'cycle{i}-results.json').exists()};assert '1' in results
qual=load('engineering-qualification.json');provenance=load('upstream-provenance.json');data=load('materialized/manifest.json');freezes=dict(base='379912673e692c7b4b7c28aa5b3a17b2bffbc0d3',method=load('data-freeze.json')['method_freeze_sha'],data=commit_for('data-freeze.json'))
sections=['# Qwen Error-Driven QLoRA Learning v0',f"Registered Cycle-1 result: **{results['1']['gate']['classification']}**."]
if '2' in results:sections.append(f"Registered Cycle-2 result: **{results['2']['gate']['classification']}**.")
sections+=['## Frozen identity',f"Branch: `research/qwen-error-driven-qlora-learning-v0`. Base `{freezes['base']}`. Method Freeze `{freezes['method']}`. Data/Split Freeze `{freezes['data']}`.",f"All arms use `Qwen/Qwen3-14B@{provenance['hf_revision']}` in the same HF/NF4 stack: BF16 quantized compute, double quantization, native nonthinking template, greedy decoding, context 1536, max new tokens 96, batch 4. M0 disables the adapter; M1/M2 enable the learned adapter. No GGUF/HF outcome comparison enters any gate.",f"LoRA r16/alpha32/dropout0/all-linear across 280 projections; {qual['trainable_parameters']:,} trainable parameters. Two fixed epochs, microbatch 1, accumulation 8, AdamW lr 1e-4, 5% warmup then linear decay. Final adapter only; validation loss is diagnostic. Complete package lock, GPU/CUDA identity and resource measurements are in `engineering-qualification.json`; exact settings in `runtime-settings.json`; upstream hashes/template identity in `upstream-provenance.json`.",f"Synthetic qualification passed in {qual['wall_seconds']:.1f} seconds; peak allocated GPU memory {qual['peak_allocated_bytes']/2**30:.2f} GiB. An earlier pre-scientific attempt was interrupted by a reported freeze/restart; the cause was not established. Recovery reduced engineering context, capped allocations and added a resource watchdog before Method Freeze. No scientific outcomes informed these choices.",'## Prospective data','| Pool | Cases | Prior counts |\n|---|---:|---|\n'+'\n'.join(f"| {name} | {data['datasets'][name]['count']} | {', '.join(sorted(data['datasets'][name]['prior_counts'],key=int))} |" for name in ['H1','V1','T1','R1','H2','V2','T2','R2']),"Both cycles and all counterfactuals were generated before M0. Each test has 60 cases per joint output. The sealed prior-count ranges appear in neither harvest/validation/regression/neighbor pool. Ordering and package consistency cannot evade the normalized leakage checks. Abstract truth patterns and the existential operation recur; this is bounded synthetic length/composition generalization, not a new logical operation or general real-task competence."]
artifacts={};compositions={}
for cycle,res in results.items():
 i=int(cycle);sections.append(f'## Cycle {cycle}');freezes[f'H{cycle}_raw']=commit_for(f'H{cycle}-raw-freeze.json')
 if 'admission_stop' in res:
  sections.append(f"Training admission stopped: {res['admission_stop']}. Harvest errors: {res['harvest_errors']}/{res['harvest_count']}. No candidate was trained and no sealed test calls were made for this cycle.");continue
 a=load(f'M{cycle}-artifact-freeze.json');d=load(f'D{cycle}-composition.json');artifacts[cycle]=a;compositions[cycle]=d;freezes[f'M{cycle}_artifact']=commit_for(f'M{cycle}-artifact-freeze.json');freezes[f'cycle{cycle}_evaluation_raw']=commit_for(f'cycle{cycle}-evaluation-raw-freeze.json')
 sections.append(f"Harvest: {d['errors']}/{d['harvest']} verified joint errors; all were admitted. D{cycle}: {d['composition']}, totaling {d['total_exposures_per_epoch']} exposures per epoch and {d['unique_case_ids']} unique case IDs. Wrong answers were never supplied in training prompts.")
 sections.append(f"M{cycle} initial adapter SHA256 `{a['initial_adapter_files']['adapter_model.safetensors']['sha256']}`; final `{a['adapter_files']['adapter_model.safetensors']['sha256']}`. Adapter freeze commit `{freezes[f'M{cycle}_artifact']}` precedes sealed-test inference. Base unchanged: {a['base_unchanged']}; adapter changed: {a['adapter_changed']}; save/reload exact: {a['checkpoint_reload_exact']}.")
 sections.append(f"Training: {a['optimizer_steps']} updates; {a['examples_seen']} effective example exposures; {a['wall_seconds']/60:.1f} minutes; peak allocated {a['peak_allocated_bytes']/2**30:.2f} GiB; adapter {a['adapter_files']['adapter_model.safetensors']['bytes']:,} bytes. Validation losses: {a['validation_loss']}. Full training loss, gradients, learning-rate schedule and parameter fingerprints are preserved in the artifact manifest. Adapter/optimizer binaries remain in persistent local research storage, referenced by hashes; no deployment occurred.")
 if i==1 and (P/'training-recovery-audit.json').exists():
  recovery=load('training-recovery-audit.json');sections.append(f"M1 training had two interruptions: a user-reported restart after logged update 256, resumed at checkpoint 250, and a GPU telemetry command failure after update 913, resumed at checkpoint 900. The unchanged watchdog terminated training on the second interruption. The frozen recovery mechanism recomputed {recovery['logged_discarded_completed_updates']} logged completed updates ({recovery['logged_discarded_completed_exposures']} exposures). The initial adapter tensor file remained byte-identical; the JSON configuration differed only in target-module list ordering, with identical normalized contents and the same verified 280 projections. The duration above covers the resumed process only; combined recorded active training duration was at least {recovery['combined_recorded_active_seconds']/60:.1f} minutes, excluding downtime/unlogged work. Effective trajectory: {recovery['retained_optimizer_updates']} updates; at least {recovery['minimum_physical_completed_updates']} physical completed updates including discarded work. No recipe, data, candidate-selection or sealed-evaluation rule changed.")
 seen_before=0;epoch_losses={}
 for record in a['loss_curve']:
  weight=record['examples_seen']-seen_before;seen_before=record['examples_seen'];total_loss,count=epoch_losses.get(record['epoch'],(0.,0));epoch_losses[record['epoch']]=(total_loss+weight*record['loss'],count+weight)
 sections.append('Mean training loss per example by epoch: '+', '.join(f'{e}: {value/count:.8g}' for e,(value,count) in epoch_losses.items())+'. These teacher-forced engineering diagnostics do not substitute for sealed inference.')
 if i==1 and a['recovery_used']:
  sections.append('The M1 peak allocated-memory figure above covers the final resumed process only. The complete-stage resource audit reports sampled device headroom across all recorded processes; those device samples are not equivalent to a continuous PyTorch allocation maximum.')
 sections.append(table(res['comparison'],f'M{i-1}',f'M{i}'));x=res['comparison']['joint'];sections.append(f"Paired T{cycle} table: both correct {x['both_correct']}; incumbent only {x['incumbent_only']}; candidate only {x['candidate_only']}; both wrong {x['both_wrong']}. Two-sided exact McNemar p={x['mcnemar_exact_two_sided_p']:.8g}. The p-value follows the registered paired-endpoint test; it does not establish generalization beyond this synthetic generator.")
 if i==1:
  sections.append(regression(res['regression']))
  sections.append('R1 families were prospective intended strength probes. Several M0 family scores were low in this HF stack, so their labels do not establish strong baseline competence; the table reports the actual baseline. Both arms were schema-valid on every T1 case, so the observed T1 gains are semantic improvements rather than schema repair.')
  descriptive=load('descriptive-error-analysis.json')['cycles']['1']['subset_comparisons']
  lines=['### Descriptive error decomposition','These posthoc subsets do not alter any gate or candidate.','| Subset | Metric | M0 | M1 |','|---|---|---:|---:|']
  for subset,metric in [('current_UNKNOWN','current_violation'),('prior_UNKNOWN','prior_violation'),('mixed_prior_aggregation','prior_violation')]:
   x=descriptive[subset][metric];lines.append(f"| {subset} | {metric} | {x['incumbent_correct']}/{x['n']} | {x['candidate_correct']}/{x['n']} |")
  sections.append('\n\n'.join(lines[:2])+'\n\n'+'\n'.join(lines[2:]))
 else:
  sections.append('M1 was already correct on all T2 endpoints, leaving no measured headroom for the registered four-point improvement. Both incremental-gain gates fail unchanged. M2 received only three newly verified H2 errors (all prior YES predicted UNKNOWN), so this result establishes neither a second sealed improvement nor inability to learn again on a different, separately authorized task.')
  sections+=['### T1 retention',table(res['retention'],'M1','M2'),'### R1 retention',regression(res['regressions']['R1']),'### R2 regression',regression(res['regressions']['R2'])]
 sections.append('Gate checks:\n\n'+'\n'.join(f"- {k}: {'PASS' if v else 'FAIL'}" for k,v in res['gate']['checks'].items()))
 sections.append(f"Registered classification: **{res['gate']['classification']}**. Leakage audit: {res['leakage']['status']}; exact, normalized and package-ignored sealed overlaps are all zero. Abstract family overlap counts: {res['leakage']['abstract_truth_pattern_overlap_counts']}.")
first=results['1'];second=results.get('2');first_pass=first['gate']['classification']=='ERROR_DRIVEN_PARAMETER_LEARNING_SUPPORTED';second_pass=second is not None and second['gate']['classification']=='TWO_CYCLE_ERROR_DRIVEN_LEARNING_SUPPORTED'
answers=[]
answers.append('Yes for the scientific adapter(s); initial/final tensor fingerprints and artifact hashes differ.' if artifacts else 'No scientific adapter was trained; only synthetic qualification parameters changed.')
answers.append('Yes: all loaded base parameters, buffers and NF4 quantization states matched before and after each completed scientific training cycle.' if artifacts else 'No scientific update occurred; the synthetic qualification verified a frozen base.')
if 'comparison' in first:
 x=first['comparison']['joint'];answers.append(f"M1 changed sealed T1 joint accuracy by {x['gain_pp']:+.2f} points (exact paired p={x['mcnemar_exact_two_sided_p']:.8g}); the full registered learning claim {'passed' if first_pass else 'did not pass'}.")
 answers.append(f"The fixed UNKNOWN/aggregation subset changed by {first['comparison']['targeted']['gain_pp']:+.2f} points. Field and family results above define the scope of that observation.")
 answers.append('The no-major-regression gate '+('passed; interpret it using the measured baseline scores, since not every intended strength probe was strong for M0.' if first['gate']['checks']['no_major_regression'] else 'failed; see the family table.'))
 answers.append('No sealed normalized state entered training or replay. Held-out prior counts test composition beyond the harvest lengths; recurring templates and abstract logic remain shared, so broad transfer or absence of all memorization is not established.')
else:answers+=['Not tested: training admission stopped.','Not tested.','Not tested.','Prospective leakage checks passed, but no learning-generalization claim can be evaluated.']
answers.append('M2 parameters were updated from every verified M1 H2 mistake, with fixed neighbors and replay. Further sealed behavioral improvement was not demonstrated when both models reached 540/540; its second-cycle gate '+('passed.' if second_pass else 'did not pass.') if '2' in artifacts else 'Cycle 2 did not produce a trained M2; '+('the first-cycle gate did not authorize it.' if not first_pass else 'the second-cycle admission condition stopped it.'))
answers.append(f"T1 retention changed by {second['retention']['joint']['gain_pp']:+.2f} points; registered retention gate {'passed' if second['gate']['checks']['t1_retention_loss_at_most_2pp'] else 'failed'}." if second and 'retention' in second else 'Not evaluated; no M2 was produced.')
answers.append('Two-cycle error-driven parameter learning on this bounded synthetic temporal-state task.' if second_pass else 'One-cycle externally supervised error-driven parameter learning on this bounded synthetic task; a second-cycle success is not established.' if first_pass else 'The registered error-driven generalization capability is not established; any observed gains and engineering parameter changes are reported separately.')
answers.append('RSI still requires useful real tasks, authenticated consequences, autonomous diagnosis and bounded change proposals with predictions, protected authorization, implementation, sealed real-task validation, retention and repetition by the improved system. This externally designed pipeline establishes none of that autonomy.')
questions=['Did trainable parameters actually change?','Did base weights remain frozen?','Did M0 mistake training improve unseen M1 behavior?','Did targeted errors improve?','Did existing strengths survive?','Is the improvement distinguishable from memorization/leakage?','Did M2 learn from M1’s own mistakes?','Did M2 retain M1’s gains?','What exact capability is established?','What separates this from RSI?']
sections+=['## Completion questions','\n\n'.join(f'{i}. **{q}** {a}' for i,(q,a) in enumerate(zip(questions,answers),1)),'## Preservation and publication boundary',"Inherited published files and prior refs are unchanged; the promoted selector, Memory, grounded state, policy and main were not modified. The external restart cleared temporary worktrees/private files, whose recovery is not claimed. The earlier Qwen2.5-0.5B lineage and source remain intact; no historical scientific training examples were reused. Dolphin/Mixtral remains historical inference-only evidence. See `replay-audit.json`, `preservation-audit.json` and the publication audit.","Only the audited research branch is published. No merge, promotion, active-model replacement, policy modification, external deployment, RL or subsequent study occurs."]
(P/'report.md').write_text('\n\n'.join(sections)+'\n')
handoff=dict(branch='research/qwen-error-driven-qlora-learning-v0',freezes=freezes,model_repository=provenance['hf_repository'],model_revision=provenance['hf_revision'],trainable_parameters=qual['trainable_parameters'],datasets=data['datasets'],results=results,training_compositions=compositions,answers=dict(zip(questions,answers)),completed_scientific_cycles=list(artifacts),adapter_hashes={i:dict(before=a['initial_adapter_files']['adapter_model.safetensors']['sha256'],after=a['adapter_files']['adapter_model.safetensors']['sha256']) for i,a in artifacts.items()});handoff['training_recovery']=load('training-recovery-audit.json') if (P/'training-recovery-audit.json').exists() else None;dump(P/'handoff.json',handoff)
print(json.dumps(dict(classifications={i:r['gate']['classification'] for i,r in results.items()},report=str(P/'report.md'))))
