"""Post-campaign evidence audit and reporting only. No scientific inference."""
import base64,json,math,subprocess,sys,time
from pathlib import Path
ROOT=Path('/home/sotiriosc/horus-causal-machine-learning-v0');P=ROOT/'research/horus-causal-machine-learning-v0';sys.path.insert(0,str(P))
from common import *
import run,stack
from engine import verified_tapes
from audit import preflight,evidence_audit
from receipts import key
from transformers import AutoTokenizer

def forbidden(*args,**kwargs):raise AssertionError('Post-campaign audit attempted model inference/load')
stack.runtime.infer=forbidden;stack.runtime.load=forbidden

def load(name):return json.loads((P/name).read_bytes())
def commit_for(name):return git('log','-1','--format=%H','--',PREFIX+'/'+name)
def tree(rev):
 return {entry.split('\t',1)[1]:entry.split('\t',1)[0] for entry in git('ls-tree','-r',rev).splitlines()}

def audit_all():
 preflight();results={};audits={};tokenizer=AutoTokenizer.from_pretrained(stack.runtime.BASE,local_files_only=True);requests=outputs=0
 for cycle in [1,2]:
  if not (P/f'cycle{cycle}-results.json').exists():continue
  original=load(f'cycle{cycle}-results.json');before=run.public_score_hashes();run.score_harvest(cycle);assert before==run.public_score_hashes()
  if 'admission_stop' not in original:
   result=run.score_evaluation(cycle);assert result==original and before==run.public_score_hashes()
   art=load(f'C{cycle}-artifact-freeze.json');training=rows(P/f'D{cycle}.jsonl');assert art['examples_seen']==2*len(training) and art['optimizer_steps']==2*math.ceil(len(training)/8)
   for label,folder in [('initial_adapter_files',ADAPTERS/f'C{cycle}-initial'),('adapter_files',ADAPTERS/f'C{cycle}')]:
    for name,meta in art[label].items():assert filehash(folder/name)==meta['sha256'] and (folder/name).stat().st_size==meta['bytes']
  results[str(cycle)]=original
  for phase in [f'harvest{cycle}',f'evaluation{cycle}']:
   if not (P/(phase+'-raw-freeze.json')).exists():continue
   audits[phase]=evidence_audit(phase)
   for tape in verified_tapes(phase).values():
    for envelope in tape.stream.records:
     r=envelope['record']
     if envelope['kind']=='REQUEST_BATCH':
      for msgs,rendered,ids in zip(r['messages'],r['rendered_prompts'],r['prompt_token_ids']):
       assert stack.runtime.prompt(tokenizer,msgs)==rendered and tokenizer.encode(rendered,add_special_tokens=False)==ids;requests+=1
     elif envelope['kind']=='PREDICTION_BATCH':
      req=tape.index['REQUEST_BATCH',r['id']]['record'];assert len(req['messages'])==len(r['outputs'])
      for answer,rendered in zip(r['outputs'],req['rendered_prompts']):
       assert tokenizer.decode(answer['generated_token_ids'],skip_special_tokens=True)==answer['text'];assert answer['prompt_sha256']==__import__('hashlib').sha256(rendered.encode()).hexdigest();outputs+=1
 assert requests==outputs
 baseline=load('preservation-baseline.json');before=tree(baseline['base']);after=tree('HEAD');assert all(after.get(n)==v for n,v in before.items());assert all(n.startswith(PREFIX+'/') for n in set(after)-set(before))
 heads='\n'.join(x for x in git('for-each-ref','--format=%(refname) %(objectname)','refs/heads').splitlines() if not x.startswith('refs/heads/research/horus-causal-machine-learning-v0 '));assert heads==baseline['local_heads']
 remote_before={ref:sha for sha,ref in (r.split() for r in baseline['remote_heads'].splitlines())};remote_now={ref:sha for sha,ref in (r.split() for r in git('ls-remote','--heads','origin').splitlines())};assert all(remote_now.get(r)==sha for r,sha in remote_before.items())
 archives=[]
 for ref in git('for-each-ref','--format=%(refname)','refs/heads').splitlines():
  if 'private-archive' in ref:
   assert subprocess.run(['git','merge-base','--is-ancestor',ref,'HEAD'],cwd=ROOT).returncode!=0;archives.append(ref)
 dump(P/'replay-and-oracle-audit.json',dict(status='PASS',inference_calls=0,byte_identical=True,requests_verified=requests,outputs_verified=outputs,exact_semantic_messages_and_rendering_and_token_ids=True,raw_outputs_match_generated_tokens=True,phases=audits))
 dump(P/'preservation-audit.json',dict(status='PASS',inherited_files_unchanged=len(before),prior_local_heads=len(heads.splitlines()),prior_remote_heads=len(remote_before),private_archive_refs_not_reachable=archives,main_and_active_architecture_unchanged=True,scope='Only the new research directory differs from the verified base. All prior committed files and local/remote branches remain unchanged; no claim to recover previously lost temporary artifacts.'))
 resources={}
 for path in sorted((ASSETS/'monitor').glob('*.jsonl')):
  values=rows(path);resources[path.stem]=dict(samples=len(values),minimum_gpu_free_GiB=min(x['gpu_free_GiB'] for x in values),minimum_linux_available_GiB=min(x['linux_available_GiB'] for x in values),minimum_windows_free_GiB=min(x['windows_free_GiB'] for x in values),maximum_gpu_temperature_C=max(x['gpu_temperature_C'] for x in values),stops=sum(x['stop_reason'] is not None for x in values))
 dump(P/'resource-audit.json',dict(status='PASS',stages=resources,scope='Sampled device/host headroom. Per-process PyTorch peaks are in qualification and adapter manifests.'))
 return results

def report(results):
 freeze=load('world-data-freeze.json');worlds=load('materialized/manifest.json');provenance=json.loads((OLD/'upstream-provenance.json').read_bytes());artifacts={i:load(f'C{i}-artifact-freeze.json') for i in results if (P/f'C{i}-artifact-freeze.json').exists()};compositions={i:load(f'D{i}-composition.json') for i in results if (P/f'D{i}-composition.json').exists()}
 raw={p.name:commit_for(p.name) for p in P.glob('*-raw-freeze.json')};first=results['1'];second=results.get('2');supported=first['gate'].get('cycle2_authorized',False);two=bool(second and second['gate']['classification']=='TWO_CYCLE_CAUSAL_PARAMETER_LEARNING_SUPPORTED')
 text=['# Horus Causal Machine Learning v0',f"Cycle 1: **{first['gate']['classification']}**. "+(f"Cycle 2: **{second['gate']['classification']}**." if second else 'Cycle 2 was not run because the first-cycle gate did not authorize it.'), 'This is an externally orchestrated, bounded deterministic causal-machine experiment. C0 is the exact successful prior M1 adapter plus the unchanged Qwen3-14B base, not M2. It reproduced the prior temporal result at 540/540 before this study. No active adapter was promoted and this study does not establish RSI.', '## Provenance and prospective design',f"Branch: `research/horus-causal-machine-learning-v0`. Base: `{freeze.get('base_commit','9e53191f2d1a22aadb0264ab91ca929479225fec')}`. Method Freeze: `{freeze['method_freeze_sha']}`. World/Data Freeze: `{commit_for('world-data-freeze.json')}`. Simulator/DSL SHA256: `{filehash(P/'dsl.py')}`.",f"C0: Qwen/Qwen3-14B@{provenance['hf_revision']} + adapter `{C0_SHA}`. Base shard and tokenizer hashes are in `handoff.json` and the unchanged prior upstream manifest.",'Per cycle: 960 H, 240 V, 480 T, 40 sealed control machines. All 3,440 worlds and both cycles were frozen before causal inference. Each H/V/T world has one scheduled scored endpoint following 64 executed diagnostic context actions; diagnostic context is never a training target. Total prospective diagnostic actions: 220,160. Primary endpoints: 3,360 if both cycles execute. Each arm can execute up to 160 control actions per cycle. See actual phase receipt counts below.',f"Global seed: {freeze['seed']}; pool seed bases: `{canon(freeze['world_seed_bases'])}`. Each accepted case records its exact candidate seed. Sixteen diagnostic schedules are fixed in the materialized manifest.",'The finite declared hypothesis family is the Cartesian product of 4,632 sensor roots. The independent recursive checker exhaustively filters it using visible histories and rejects ambiguity. The model sees only opaque port names, observed interventions and a candidate action. Hidden programs, states, graphs, oracle labels and family names are excluded from prompts and the planner. Whole-machine normalized graph, exact behavioral equivalence, seed, history and endpoint overlaps are zero across all pools. Test/control machines have strictly larger component/depth/delay/state counts within each corresponding family. Primitive motifs and generator templates remain shared; this is not arbitrary-logic transfer or proof against all template learning.', '## Raw-first evidence', '\n'.join(f'- `{name}`: `{sha}`' for name,sha in sorted(raw.items()))]
 oracle=load('replay-and-oracle-audit.json');text.append('Actual execution and request counts (excluding the initial diagnostic context and incumbent reproduction):\n\n| Phase | Causal prediction calls | Actual scored executions | Unexecuted control alternatives |\n|---|---:|---:|---:|\n'+'\n'.join(f"| {phase} | {a['causal_model_requests']} | {a['actual_scored_executions']} | {a['unexecuted_control_alternatives_without_labels']} |" for phase,a in oracle['phases'].items()))
 for i,r in results.items():
  text.append(f'## Cycle {i}')
  if 'admission_stop' in r:text.append(f"Training admission stopped: `{r['admission_stop']}`; verified errors {r['harvest_errors']}. No candidate or sealed evaluation was run.");continue
  a=artifacts[i];d=compositions[i];x=r['comparison']['exact'];control=r['control'];temporal=r['temporal_retention'];text += [f"Harvest errors E{i}: {d['errors']}/{d['harvest']}; D{i}: `{canon(d['composition'])}` = {d['exposures_per_epoch']} exposures/epoch. Every authenticated error was admitted. Correct replay uses replacement; counts are exposures, not additional unique machines. No unexecuted causal alternatives or hidden-program targets entered training.",f"C{i} continued C{int(i)-1}. Initial adapter SHA256 `{a['initial_adapter_files']['adapter_model.safetensors']['sha256']}`; final `{a['adapter_files']['adapter_model.safetensors']['sha256']}`. Base unchanged: {a['base_unchanged']}; adapter changed: {a['adapter_changed']}; trainable parameters {a['trainable_parameters']:,}; epochs {a['epochs']}; optimizer steps {a['optimizer_steps']}; examples seen {a['examples_seen']}; training seconds {a['wall_seconds']:.2f}; peak allocated GiB {a['peak_allocated_bytes']/2**30:.3f}. Save/reload exact: {a['checkpoint_reload_exact']}. Loss, gradient, validation, recovery and memory records are in the artifact manifest.",f"Prediction exact: **{x['incumbent_correct']}/{x['n']} → {x['candidate_correct']}/{x['n']}**, gain **{x['gain_pp']:+.2f}pp**, exact paired two-sided McNemar p={x['mcnemar_exact_two_sided_p']:.9g}. Paired table: both correct {x['both_correct']}, incumbent-only {x['incumbent_only']}, candidate-only {x['candidate_only']}, both wrong {x['both_wrong']}. Bit accuracy: {100*r['comparison']['incumbent_bit_accuracy']:.2f}% → {100*r['comparison']['candidate_bit_accuracy']:.2f}%. Schema: {r['comparison']['schema']['incumbent_correct']}/{x['n']} → {r['comparison']['schema']['candidate_correct']}/{x['n']}."]
  for field,groups in r['comparison']['strata'].items():
   text.append(f'### {field}\n\n| Stratum | Incumbent | Candidate | Gain pp |\n|---|---:|---:|---:|\n'+'\n'.join(f"| {name} | {v['incumbent_correct']}/{v['n']} | {v['candidate_correct']}/{v['n']} | {v['gain_pp']:+.2f} |" for name,v in groups.items()))
  text += [f"Control: **{control['incumbent_correct']}/40 → {control['candidate_correct']}/40**, paired p={control['mcnemar_exact_two_sided_p']:.9g}; classification **{control['classification']}**. Each arm's mean actions conditional on success: {control['incumbent_mean_actions_to_success']} → {control['candidate_mean_actions_to_success']}; common-success means ({control['common_successes']} worlds): {control['common_success_incumbent_mean_actions']} → {control['common_success_candidate_mean_actions']}. Cumulative actual selected-action prediction errors: {control['incumbent_cumulative_prediction_errors']} → {control['candidate_cumulative_prediction_errors']}. Per-world failure modes appear in the control score files. The planner is fixed depth-one/width-four/Hamming/tie-order/budget-four; this claim is separate from prediction learning.",f"Prior temporal retention: **{temporal['joint_correct']}/540**, schema **{temporal['schema_valid']}/540**, loss {temporal['loss_pp']:.2f}pp. The frozen criterion requires >=530 exact and 540 valid."]
  if 'cycle1_retention' in r:
   ret=r['cycle1_retention']['exact'];text.append(f"Causal T1 retention: {ret['incumbent_correct']}/{ret['n']} → {ret['candidate_correct']}/{ret['n']} ({ret['gain_pp']:+.2f}pp). Full old-family/depth/delay/state retention strata are in the result JSON.")
  text.append('Gate checks:\n\n'+'\n'.join(f"- {k}: {'PASS' if v else 'FAIL'}" for k,v in r['gate']['checks'].items()));text.append(f"Registered classification: **{r['gate']['classification']}**.")
 questions=['Did C0 learn a causal prediction capability from executed mistakes?','Did that improvement generalize to structurally unseen machines?','Did improved prediction produce better goal-directed control?','Did C1 preserve the prior temporal capability?','Did C1 encounter genuinely new errors in the harder Cycle-2 family?','Did C2 learn from those errors?','Did C2 preserve Cycle-1 gains?','Is the improvement distinguishable from exact/template memorization?','What exact new capability is established?','What still separates this system from RSI?']
 answers=[('Yes, under the full registered Cycle-1 gate.' if supported else 'The registered causal prediction learning claim was not established; the measured changes and failed gates above define the result.'),('Yes within the frozen grammar, on larger machines with disjoint whole-machine programs/behavior/histories.' if supported else 'Structurally held-out performance was measured, but the full registered learning claim was not established.'),('Yes under the separate control gate.' if first.get('control',{}).get('classification')=='CAUSAL_CONTROL_BENEFIT_SUPPORTED' else 'The registered control benefit was not established.'),('Yes.' if first.get('temporal_retention',{}).get('joint_correct',0)>=530 and first.get('temporal_retention',{}).get('schema_valid')==540 else 'No under the registered criterion; see retention results.' if 'temporal_retention' in first else 'Not evaluated because training admission stopped.'),(f"H2 contained {compositions['2']['errors']} authenticated C1 errors in prospectively new stateful families." if '2' in compositions else 'Not tested; Cycle 2 did not proceed.'),('Yes under all registered Cycle-2 gates.' if two else 'A second causal learning improvement was not established.' if second else 'Not tested.'),(f"T1 changed {second['cycle1_retention']['exact']['gain_pp']:+.2f}pp; interpret alongside old-stratum and schema gates." if second and 'cycle1_retention' in second else 'Not tested.'),'Exact program/behavior/history memorization is excluded by structural disjointness. Shared primitive motifs and generator templates remain, so this cannot exclude all template-based learning.',('Two externally orchestrated cycles of consequence-grounded parameter learning on unseen machines within this bounded grammar, with registered retention.' if two else 'One externally orchestrated cycle of consequence-grounded causal prediction learning within the bounded grammar; any control claim is stated separately.' if supported else 'No new causal-learning capability met the full registered gate. Engineering qualification and authenticated execution are demonstrated separately.'),'Horus did not autonomously diagnose a limitation, propose/predict an intervention, obtain authorization, build and promote a verified improvement, then repeat as the improved system. The external experiment supplies orchestration; even a positive result would not establish RSI.']
 if (P/'descriptive-results.json').exists():
  descriptive=load('descriptive-results.json');baseline=descriptive['prediction']['C1-T1']['persistence_baseline_exact']
  text += ['## Interpretation and descriptive checks', 'Unlike the prior temporal task, which applied one fixed global proposition/aggregation rule, each machine here has a different hidden dynamical program. The intended capability is to use executed intervention history to predict that unfamiliar system. The present result does not establish the full registered capability.', f'A posthoc, zero-inference persistence reference (predict the last observed sensor state, ignoring the action) scored {baseline}/480, versus C1 at 273/480. This reference was not preregistered and changes no gate. It shows that much of the test can be answered by persistence; the small advantage over it is insufficient to claim robust causal inference. See `descriptive-results.json` for per-sensor-position counts and frozen target distributions.', 'Structural complexity did not guarantee higher measured difficulty: C0 scored 177/960 (18.44%) on H1 and 249/480 (51.88%) on the larger T1 machines. The distributions differ in compositions and resulting behavior; do not interpret the larger structures as uniformly harder empirical cases. Whole-machine disjointness excludes exact case reuse, while shared motifs and local persistence remain possible explanatory shortcuts.', 'Control used 144 actual actions for C0 and 137 for C1. Failures were action-budget exhaustion: 32/40 for C0 and 29/40 for C1. Neither arm selected a schema-invalid prediction.']
 text += ['## Completion questions','\n\n'.join(f'{i}. **{q}** {a}' for i,(q,a) in enumerate(zip(questions,answers),1)),'## Audits and boundaries','Raw evidence was committed before scoring, matched receipt bundles authenticate executed targets, and post-campaign scoring reproduced byte-identical outputs with zero inference. Exact prompts and generated token decoding were independently checked. All inherited files and prior local/remote branch heads are preserved. Secret-free reachable-history audit precedes publication. Private world state, raw signed streams, authority key, raw model output, adapters and optimizer/recovery binaries remain local. No merge, architecture/model promotion, next study or additional scientific campaign follows this result.']
 (P/'report.md').write_text('\n\n'.join(text)+'\n')
 dump(P/'handoff.json',dict(branch='research/horus-causal-machine-learning-v0',verified_base_sha='9e53191f2d1a22aadb0264ab91ca929479225fec',method_freeze_sha=freeze['method_freeze_sha'],world_data_freeze_sha=commit_for('world-data-freeze.json'),raw_pre_score_shas=raw,simulator_dsl_sha256=filehash(P/'dsl.py'),seed=freeze['seed'],world_seed_bases=freeze['world_seed_bases'],C0=dict(repository=provenance['hf_repository'],revision=provenance['hf_revision'],adapter_sha256=C0_SHA,base_shard_hashes=provenance['safetensor_hashes'],tokenizer_and_config_hashes=provenance['files']),world_counts=freeze['world_counts'],prospective_diagnostic_transitions=220160,actual_execution_counts=oracle['phases'],compositions=compositions,adapter_hashes={i:dict(before=a['initial_adapter_files']['adapter_model.safetensors']['sha256'],after=a['adapter_files']['adapter_model.safetensors']['sha256']) for i,a in artifacts.items()},results=results,answers=dict(zip(questions,answers)),descriptive_analysis=load('descriptive-results.json') if (P/'descriptive-results.json').exists() else None,publication_sha='Recorded in remote-verification receipt and final response after audited push; a commit cannot contain its own SHA.'))

if __name__=='__main__':
 result=audit_all();report(result);print(canon(dict(status='PASS',classifications={i:r['gate']['classification'] for i,r in result.items()})))
