from pathlib import Path
import json
P=Path(__file__).resolve().parent
def dump(n,v):(P/n).write_text(json.dumps(v,indent=2)+'\n')
def obj(properties):return dict(type='object',properties=properties,required=list(properties),additionalProperties=False)
s={'type':'string','minLength':1};ids={'type':'array','items':s,'minItems':1,'uniqueItems':True};strings={'type':'array','items':s};boolean={'type':'boolean'}
diagnosis=obj(dict(diagnosis_id=s,statement=s,type={'enum':['OBSERVED_PROBLEM','EVIDENCE_GAP']},current_relevance=s,evidence_ids=ids,system_versions_used={'type':'array','items':{'enum':['PRE_S','S_ACTIVE','S_PLUS_E_ACTIVE']},'minItems':1,'uniqueItems':True},already_addressed_by_S=boolean,already_addressed_by_E=boolean,observed=strings,inferred=strings,unknown=strings,falsifier=s,minimum_new_evidence_needed=s))
schemas={'A':obj(dict(diagnoses={'type':'array','items':diagnosis,'minItems':0,'maxItems':3},no_supported_diagnosis=boolean)),'B':obj(dict(selected_diagnosis_id=s,why_selected=s,evidence_ids=ids,main_uncertainty=s,falsifier=s,next_information_needed=s)),'C':obj(dict(fatal_objection=boolean,objections=strings,evidence_ids={'type':'array','items':s,'uniqueItems':True}))}
system='You are an isolated diagnosis-only analysis component. MODEL INTERPRETATION != MECHANICAL POLICY EXECUTION. Software facts and public observed outcomes are authoritative within their stated version and evidence maturity. UNKNOWN stays unknown. Distinguish observation, inference and missing evidence. Do not emulate policy predicates, infer hidden outcomes, invent facts, propose solutions, write code, change rules/thresholds/models, or claim policy authority. No diagnosis is required. Return only the requested final JSON schema; native reasoning is private.'
prompts={'A':'Identify zero to three CURRENT unresolved structural problems or evidence gaps supported by this broad dossier. You are not told which problem to find. Respect version tags and promoted scopes: historical solved problems alone do not establish current failure. Missing evidence is not demonstrated behavioral failure. Evidence IDs must cite supplied records. State a falsifier and minimum information needed, without a proposal or experimental prescription. Use concise prose, at most about 160 words per diagnosis. An empty diagnoses list with no_supported_diagnosis=true is valid. Do not reward novelty.', 'B':'Select exactly one of the surviving diagnoses based on evidence strength, current relevance, falsifiability, boundedness and minimal scope. Select its exact ID without changing the diagnosis. Explain the selection briefly; cite supplied evidence only. Request information, not a solution or policy candidate.', 'C':'Find reasons this selected diagnosis may be unsupported, obsolete, already solved, or merely an evidence gap. Evaluate exact cited evidence and the solved registry. An accurately labeled evidence gap is not itself a fatal objection. Do not rewrite the diagnosis, propose a fix, or invent contrary evidence. fatal_objection=true only for a stated factual objection; objections may include nonfatal limits.'}
dump('analysis-protocol.json',dict(system=system,prompts=prompts,schemas=schemas))
cfg=json.loads((P.parent/'agent-self-model-grounding-v0.1/analysis-configuration.json').read_text());cfg.update(seed=42021,endpoint='http://127.0.0.1:18084',max_analysis_calls=3,max_tokens=4096)
dump('analysis-configuration.json',cfg)
