"""Read-only source introspection and projections of already-public evidence.

Never constructs SessionStore/Memory, runs a selector, or executes a world.
Only the existing pure select_route function is evaluated on archived assessments.
"""
from pathlib import Path
import ast,hashlib,json,subprocess,sys
P=Path(__file__).resolve().parent;ROOT=P.parents[1];sys.path.insert(0,str(ROOT))
from experiments.grounded_authority_autonomous_agent_v0.protocol import select_route
PARENT='ecd097af2f007cb431e3ae736832960f86805deb'
PROMOTION='69947aa243a69e7ae26db534727a7122922d978d'
def sha(b):return hashlib.sha256(b).hexdigest()
def read(path):return json.loads((ROOT/path).read_text())
def dump(name,value):(P/name).write_text(json.dumps(value,indent=2)+'\n')
def constant(path,name):
 tree=ast.parse((ROOT/path).read_text())
 return next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id==name for t in n.targets))
def main():
 source_index=[]
 def bind(eid,path):
  b=(ROOT/path).read_bytes();source_index.append(dict(evidence_id=eid,path=path,sha256=sha(b)));return b
 promotion=read('research/empirical-evidence-acquisition-promotion-v0/promotion-record.json')
 for eid,path in [('ARCH-SELECTOR','grounded_agent/empirical_policy.py'),('ARCH-ENTRY','grounded_agent/__init__.py'),('ARCH-ADAPTER','grounded_agent/empirical_adapter.py'),('ARCH-ROLLBACK','grounded_agent/policy.py'),('ARCH-ROUTE','experiments/grounded_authority_autonomous_agent_v0/protocol.py'),('ARCH-S','experiments/grounded_stagnation_escape_evaluation_v0/candidate.py'),('ARCH-E','experiments/empirical_evidence_acquisition_proposal_v0/candidate.py'),('ARCH-CORE','grounded_state/core.py'),('ARCH-PROMOTION','research/empirical-evidence-acquisition-promotion-v0/promotion-record.json'),('ARCH-COMPONENTS','research/agent-self-model-grounding-v0.1/architecture-manifest.json')]:bind(eid,path)
 for row in source_index:
  assert subprocess.check_output(['git','show',PARENT+':'+row['path']],cwd=ROOT)==(ROOT/row['path']).read_bytes()
 selector=ast.parse((ROOT/'grounded_agent/empirical_policy.py').read_text());fn=next(n for n in selector.body if isinstance(n,ast.FunctionDef) and n.name=='integrated_decide')
 calls=[(n.lineno,ast.unparse(n.func)) for n in ast.walk(fn) if isinstance(n,ast.Call)];calls.sort()
 assert [line for line,call in calls if call=='authenticated_projection'][0] < [line for line,call in calls if call=='incumbent.context'][0]
 assert ast.unparse(fn).index("context['route']['route'] == 'MECHANICAL'") < ast.unparse(fn).index('incumbent.escape_choice') < ast.unparse(fn).index('recommendation')
 assert 'decide = integrated_decide' in (ROOT/'grounded_agent/__init__.py').read_text()
 previous=read('research/agent-self-model-grounding-v0.1/architecture-manifest.json')
 arch=dict(evidence_id='ARCHITECTURE',system_version='S_PLUS_E_ACTIVE',evidence_maturity='CURRENT_ARCHITECTURE',active_selector=promotion['active_selector'],routing_precedence=['GROUNDED_MECHANICAL_AUTHORITY','S_BOUNDED_STAGNATION_ESCAPE','E_EMPIRICAL_EVIDENCE_ACQUISITION','ORDINARY_MODEL_ROUTE'],rollback_selector=promotion['rollback_selector'],S_status='PROMOTED_ACTIVE',E_status='PROMOTED_ACTIVE',architecture_chain=['authenticated experience','grounded-state derivation','grounded mechanical authority','S','E','ordinary model/mixed route','protected execution','authenticated consequence','durable Memory'],components=[{k:c[k] for k in ['component_id','status','role','can_select_action','can_execute_world','can_write_memory','uses_model_call_when_triggered']} for c in previous['components']],mechanical_authority_is_S=False,S_is_E=False,precondition='Authenticated projection validates before route selection; malformed evidence fails closed.',joint_eligibility='When mechanical route is unresolved, simultaneous S/E eligibility raises IntegrationInvariantError with no action or model request.',S_scope='Frozen deterministic established-zero authenticated fallback suffix; unseen alternative; no established +1; model-free when triggered.',E_scope='Frozen empirical same-relation self-loop suffix and full window; allowed stable/variable kind, no possible change, recent and cumulative sums nonpositive, true unseen alternative, no established +1; model-free when triggered.',ordinary_model='Historical Dolphin reference/incumbent; Qwen action substitution NOT_PROMOTED.',evidence_ids=[s['evidence_id'] for s in source_index],interpretation_boundary='MODEL INTERPRETATION != MECHANICAL POLICY EXECUTION')
 dump('architecture-state.json',arch)
 # Neutral fixed inventory. Short factual summaries, not diagnoses or recommendations.
 spec=[
 ('REDUCER','PRE_S','HISTORICAL','research/agent-led-self-improvement-proposal-v0/sources/EVID-REDUCER.md','SPEED_ROBUSTNESS_TRADEOFF','Four frozen sequences compared model, latest receipt and recent-three reducers. Speed and robustness traded off; no universal predictor superiority was established.'),
 ('UNCERTAINTY','PRE_S','HISTORICAL','research/grounded-uncertainty-state-v0/report.md','EXPLICIT_UNCERTAINTY_SUPPORTED','Explicit unresolved change separated a first contradiction from established new knowledge. This did not establish best point prediction or indefinite persistence.'),
 ('HYBRID','PRE_S','HISTORICAL','research/grounded-hybrid-controller-v0/report.md','GROUNDED_HYBRID_SUPPORTED','Grounded exact experienced relations replaced model prediction; unresolved evidence could lead to abstention. Protected execution and authenticated Memory remained authoritative.'),
 ('FALLBACK','PRE_S','HISTORICAL','research/grounded-safe-fallback-v0/report.md','SAFE_FALLBACK_SUPPORTED','Established-neutral fallbacks acted without claiming optimality. The campaign demonstrated safe neutral outcomes within its finite registered cases, not immunity to stale evidence.'),
 ('EMPIRICAL','PRE_S','HISTORICAL','research/grounded-stochastic-relation-v0/report.md','EMPIRICAL_GROUNDING_SUPPORTED','Frozen empirical traces distinguished variability and possible change, with no false stability claim. Public semantic replay does not authenticate omitted private signed streams.'),
 ('AUTO02','PRE_S','HISTORICAL','research/grounded-autonomous-agent-v0.2/result.md','VALID','Ninety valid actions and original authenticated receipts; exact Memory replay and restart passed. Grounding use was weak or inconsistent. Earlier autonomous pilots remained INVALID. No causal baseline comparison was run.'),
 ('AUTHORITY','PRE_S','HISTORICAL','research/grounded-authority-autonomous-agent-v0/result.md','GROUNDED_AUTHORITY_SUPPORTED','Exact negative-known choices with a better established alternative were eliminated. Run C repeated neutral fallback while alternatives remained unseen. Broader uncertain choices were not eliminated.'),
 ('S-EVAL','PRE_S','PROSPECTIVE_SUPPORTED','research/grounded-stagnation-escape-evaluation-v0/result.md','STAGNATION_ESCAPE_SUPPORTED','Experimental S acquired missing relation evidence at the registered boundary without an action-model call. Incumbent remained unchanged during evaluation; evidence acquisition was the primary endpoint, not reward.'),
 ('S-REPLICATION','PRE_S','PROSPECTIVE_SUPPORTED','research/grounded-stagnation-escape-replication-v0/result.md','COST_OR_SCOPE_BLOCKS_PROMOTION','Acquisition replicated in eligible cases with mixed realized consequences and limited later reuse. This intermediate classification remains unchanged despite later promotion evidence.'),
 ('S-CONTROLLED','PRE_S','PROSPECTIVE_SUPPORTED','research/grounded-stagnation-escape-promotion-controlled-v0/result.md','MORE_EVIDENCE_REQUIRED','Controlled stochastic pairing preserved its original evidence-limited classification. It did not automatically activate S.'),
 ('S-ELIGIBILITY','PRE_S','PROSPECTIVE_SUPPORTED','research/grounded-stagnation-escape-eligibility-completion-v0/result.md','PROMOTE_S','Eligibility completion supplied the later bounded promotion recommendation for the exact frozen rule.'),
 ('S-PROMOTION','S_ACTIVE','CURRENT_ARCHITECTURE','research/grounded-stagnation-escape-promotion-v0/promotion-record.md','PROMOTED','External approval activated the exact frozen S. The promotion itself was not a new scientific campaign.'),
 ('QWEN-QUAL','S_ACTIVE','ENGINEERING_ONLY','engineering/grounded-agent-development-runtime-v0/qualification.md','DEVELOPMENT_RUNTIME_QUALIFIED','Pinned Qwen runtime qualified for isolated engineering work. Qualification did not transfer historical Dolphin behavior or authorize model promotion.'),
 ('QWEN-SUB','S_ACTIVE','HISTORICAL','research/qwen3-grounded-agent-substitution-v0/result.md','QWEN_FAST_BUT_BEHAVIORALLY_UNSUITABLE','Autonomous Qwen substitution was faster but collapsed to HOLD in all Qwen runs. Dolphin remained the reference/incumbent. E was not active.'),
 ('QWEN-THINK','S_ACTIVE','ENGINEERING_ONLY','research/qwen3-thinking-action-audit-v0/result.md','INTERFACE_INCOMPATIBLE','The frozen output cap was exhausted in the reasoning channel, leaving no final action. The parser rejected it and no world action ran.'),
 ('QWEN-BOUND0','S_ACTIVE','INVALID_STUDY','research/qwen3-bounded-thinking-action-v0/result.md','INVALID','Fixture preparation violated the no-world-execution boundary. Interface observations do not repair validity and cannot serve as successful behavioral evidence.'),
 ('QWEN-BOUND1','S_ACTIVE','DIAGNOSTIC_ONLY','research/qwen3-bounded-thinking-action-v0.1/result.md','QWEN_BOUNDED_THINKING_SEMANTIC_GATE_PASSED','Read-only matched contexts showed grounded-value and status responsiveness across action-order permutations. This was not autonomous performance or a general exploration-policy result.'),
 ('QWEN-R128','S_ACTIVE','HISTORICAL','research/qwen3-r128-autonomous-grounded-agent-v0/result.md','QWEN_R128_STILL_POLICY_LIMITED','All 90 model-mediated actions were HOLD despite bounded reasoning and accumulating experience. No deterministic S opportunity or mechanical ceiling arose; E was not active. Semantic responsiveness did not transfer to this sequential campaign.'),
 ('E-DIAGNOSIS','S_ACTIVE','DIAGNOSTIC_ONLY','research/empirical-information-stagnation-diagnosis-v0/result.md','EMPIRICAL_STAGNATION_DIAGNOSIS_SUPPORTED','A read-only historical analysis identified deteriorated empirical repetitions with missing relation evidence in the pre-E traces. It did not establish hidden alternative-action outcomes or reward gain.'),
 ('E-EVAL','S_ACTIVE','PROSPECTIVE_SUPPORTED','research/empirical-evidence-acquisition-evaluation-v0/result.md','EMPIRICAL_EVIDENCE_ACQUISITION_SUPPORTED','Frozen E triggered in six eligible cases and stayed silent in twelve controls. All 270 receipts were authorized. Both arms were model-free; the registered continuation control was not the deployed incumbent.'),
 ('E-REPLICATION','S_ACTIVE','PROSPECTIVE_SUPPORTED','research/empirical-evidence-acquisition-replication-v0/result.md','EMPIRICAL_EVIDENCE_ACQUISITION_REPLICATED','Across 26 matched cases, nine eligible cases triggered and seventeen boundary controls stayed silent. Missing-relation evidence was acquired; zero model calls. Mechanism replication did not establish overall autonomous reward improvement.'),
 ('E-PROMOTION','S_PLUS_E_ACTIVE','CURRENT_ARCHITECTURE','research/empirical-evidence-acquisition-promotion-v0/result.md','E_PROMOTED','The active alias changed to integrated_decide. Sixty-one tests passed before and after activation. Disposable unit fixtures were engineering checks, not a scientific campaign or autonomous run.'),
 ('SELF-V0','S_PLUS_E_ACTIVE','DIAGNOSTIC_ONLY','research/agent-led-self-improvement-proposal-v0/result.md','AGENT_SELF_MODEL_GROUNDING_FAILED','Architecture reconstruction failed: quotation fidelity and mechanical-authority/S conflation. Diagnosis and proposal were NOT_RUN. This was an analysis-component result, not an active-action campaign.'),
 ('SELF-V01','S_PLUS_E_ACTIVE','DIAGNOSTIC_ONLY','research/agent-self-model-grounding-v0.1/result.md','AGENT_SELF_MODEL_GROUNDING_FAILED','Phase A passed 104 checks with correct authority distinctions, precedence and rollback. Phase B matched 13 of 20 synthetic cases and failed material routing/model-call predicates. The overall failure is unchanged; no autonomous execution occurred.')]
 evidence=[]
 for eid,ver,maturity,path,status,summary in spec:
  sid='EVID-'+eid;raw=bind(sid,path).decode();assert status in raw,(sid,status)
  evidence.append(dict(evidence_id=sid,system_version=ver,evidence_maturity=maturity,classification=status,summary=summary,current_transfer='UNKNOWN; historical behavior is not current failure proof' if ver!='S_PLUS_E_ACTIVE' else 'Limited to the stated architecture or diagnostic scope'))
 # Attach addressed-scope annotations without rewriting historical classifications.
 for e in evidence:
  if e['evidence_id'] in ['EVID-FALLBACK','EVID-AUTHORITY']:
   e['addressed_scope']=dict(status='HISTORICAL_PROBLEM_NOW_ADDRESSED',by='S',scope='Only deterministic established-zero stagnation in the frozen S eligibility domain.')
  if e['evidence_id'] in ['EVID-QWEN-SUB','EVID-QWEN-R128','EVID-E-DIAGNOSIS']:
   e['addressed_scope']=dict(status='HISTORICAL_PROBLEM_NOW_ADDRESSED',by='E',scope='Only deteriorated empirical stagnation with missing evidence satisfying frozen E; not all repeated HOLD or all model limitations.')
  if e['evidence_id']=='EVID-AUTO02':
   e['addressed_scope']=dict(status='HISTORICAL_PROBLEM_NOW_ADDRESSED',by='GROUNDED_MECHANICAL_AUTHORITY',scope='Exact deterministic negative-known choice when a better established alternative exists; not all uncertain behavior.')
  if e['evidence_id'].startswith('EVID-S-') and e['system_version']=='PRE_S':e['experimental_arm']='FROZEN_S_CANDIDATE; not yet active incumbent'
  if e['evidence_id'] in ['EVID-E-EVAL','EVID-E-REPLICATION']:e['experimental_arm']='FROZEN_E_CANDIDATE versus registered continuation; not post-promotion incumbent'
 # Fixed endpoints of each run, independent of outcomes. No private stream is opened.
 records=[]
 for eid,path,version in [('DEC-AUTHORITY','research/grounded-authority-autonomous-agent-v0/public-result.json','PRE_S'),('DEC-R128','research/qwen3-r128-autonomous-grounded-agent-v0/public-result.json','S_ACTIVE')]:
  bind(eid,path);data=read(path)
  for run,r in sorted(data['runs'].items()):
   for idx in [0,-1]:
    d=r['decisions'][idx];a=d.get('assessments',d.get('grounded_assessments_before'));route=select_route(a)
    if 'policy_route' in d:assert route['route']==d['policy_route']
    actual=d['decision_source'];compact={action:{k:v for k,v in x.items() if k in ['relation_type','kind','observation_count','established_value','possible_change','recent_window']} for action,x in a.items()}
    suffix=d.get('suffix_before');s=False if version=='PRE_S' or (suffix is not None and suffix['count']<constant('experiments/grounded_stagnation_escape_evaluation_v0/candidate.py','THRESHOLD')) else 'UNKNOWN'
    records.append(dict(evidence_id=eid+'-'+d['decision_id'],source_evidence_id=eid,decision_id=d['decision_id'],system_version=version,evidence_maturity='HISTORICAL',state=d['state'],grounded_assessments=compact,mechanical_route=route['route']=='MECHANICAL',S_eligible=s,E_eligible=False,E_presence='NOT_ACTIVE_IN_THIS_VERSION',S_basis='Not active' if version=='PRE_S' else 'Recorded suffix below frozen threshold; sufficient to exclude eligibility',actual_route=actual,selected_action=d.get('action',d.get('selected_action')),realized_consequence=d.get('consequence',d.get('realized',{}).get('consequence')),receipt_authenticated='UNKNOWN',memory_admitted='UNKNOWN',provenance_note='Public campaign reports authenticated admission; raw signed streams are omitted, so no new cryptographic authentication is claimed.'))
 dump('versioned-behavioral-dossier.json',dict(evidence=evidence,decision_records=records,selection_rule='Complete fixed study-family inventory; first and last archived decision of every authority and R128 run. No outcome-based selection.',versions={'PRE_S':'S and E not yet promoted; grounded authority itself introduced within this era. Consult study-specific scope.','S_ACTIVE':'Grounded authority plus S incumbent, E not yet promoted; candidate arms labeled separately.','S_PLUS_E_ACTIVE':'Current promoted integrated selector. Engineering/diagnostic results are not autonomous behavior.'}))
 # Enumerate the complete preserved post-E lineage; absence is bounded to this repository snapshot.
 commits=subprocess.check_output(['git','log','--format=%H',PROMOTION+'..'+PARENT],cwd=ROOT).decode().splitlines()
 changed=subprocess.check_output(['git','diff','--name-only',PROMOTION,PARENT],cwd=ROOT).decode().splitlines()
 assert changed and all(n.startswith(('research/agent-led-self-improvement-proposal-v0/','research/agent-self-model-grounding-v0.1/')) for n in changed)
 gap=dict(evidence_id='GAP-POST-E',system_version='S_PLUS_E_ACTIVE',evidence_maturity='CURRENT_ARCHITECTURE',status='NO_PROSPECTIVE_DATA',evidence_gap='No autonomous scientific campaign using the newly promoted S+E incumbent is present in this preserved publication lineage.',scope='Repository lineage through '+PARENT+' only; not a claim about unknown external work.',basis=['EVID-E-PROMOTION','EVID-SELF-V0','EVID-SELF-V01'],not_evidence_of_failure=True)
 dump('evidence-gap-register.json',dict(items=[gap],lineage_inventory=dict(base=PROMOTION,head=PARENT,post_promotion_commits=commits,changed_path_count=len(changed),changed_directories=sorted({str(Path(n).parent) for n in changed}))))
 registry=[('deterministic established-zero stagnation','PROMOTED_ADDRESSED','S',['ARCH-S','EVID-S-PROMOTION']),('deteriorated empirical stagnation plus missing evidence','PROMOTED_ADDRESSED','E',['ARCH-E','EVID-E-PROMOTION']),('exact deterministic grounded mechanical authority','PROMOTED_ADDRESSED','GROUNDED_MECHANICAL_AUTHORITY',['ARCH-ROUTE','EVID-AUTHORITY']),('explicit unresolved deterministic change','PROMOTED_ADDRESSED','GROUNDED_DETERMINISTIC_STATE',['EVID-UNCERTAINTY']),('empirical/deterministic distinction','PROMOTED_ADDRESSED','GROUNDED_EMPIRICAL_STATE',['EVID-EMPIRICAL']),('authenticated durable Memory','PROMOTED_ADDRESSED','AUTHENTICATED_MEMORY',['ARCH-CORE']),('Horus active architecture','PARKED_NOT_ACTIVE','Horus',['STATUS-CORE']),('Zakhor keeper architecture','PARKED_NOT_ACTIVE','Zakhor',['STATUS-CORE']),('Qwen active-model substitution','NOT_PROMOTED','ORDINARY_MODEL_ROUTE',['EVID-QWEN-SUB','EVID-QWEN-R128']),('historical Dolphin reference/incumbent','ACTIVE_REFERENCE','ORDINARY_MODEL_ROUTE',['EVID-QWEN-R128'])]
 bind('STATUS-CORE','research/grounded-state-core-v0/architecture.md')
 dump('solved-problem-registry.json',dict(evidence_id='REGISTRY',system_version='S_PLUS_E_ACTIVE',evidence_maturity='CURRENT_ARCHITECTURE',items=[dict(issue=i,status=s,component=c,evidence_ids=ids) for i,s,c,ids in registry],scope_caveat='Addressed applies only within frozen scopes, not universal performance. No human-selected unresolved diagnosis is supplied.'))
 bind('CONST-SOURCE','research/empirical-information-stagnation-diagnosis-v0/constraint-provenance.md');bind('CONST-E-SOURCE','research/empirical-evidence-acquisition-proposal-v0/constraint-provenance.md')
 dump('constraint-provenance.json',dict(evidence_id='CONSTRAINTS',items=[dict(name='S threshold',value=constant('experiments/grounded_stagnation_escape_evaluation_v0/candidate.py','THRESHOLD'),provenance='EMPIRICALLY_SUPPORTED_RULE',evidence_ids=['ARCH-S','CONST-SOURCE']),dict(name='E empirical window and suffix',value=constant('grounded_state/empirical.py','WINDOW'),provenance='Existing empirical-state parameter / bounded evidence-supported rule; originally an experiment control',evidence_ids=['ARCH-E','CONST-E-SOURCE']),dict(name='Historical autonomous decision horizon',value=30,provenance='SCIENTIFIC_EXPERIMENT_CONTROL; not a learned stopping rule',evidence_ids=['CONST-SOURCE']),dict(name='Historical v0.2 action/commentary/review caps',value=[48,192,512],provenance='SCIENTIFIC_EXPERIMENT_CONTROL; no optimality claim',evidence_ids=['CONST-SOURCE']),dict(name='Historical R128 reasoning/completion/context',value=[128,768,8192],provenance='SCIENTIFIC_EXPERIMENT_CONTROL; model interface, not policy eligibility',evidence_ids=['CONST-SOURCE']),dict(name='Authenticated receipt and Memory boundary',provenance='ARCHITECTURAL_INVARIANT',evidence_ids=['ARCH-CORE','ARCH-ADAPTER'])]))
 for source in source_index:
  match=next((e for e in evidence if e['evidence_id']==source['evidence_id']),None)
  source['evidence_maturity']=match['evidence_maturity'] if match else 'HISTORICAL' if source['evidence_id'].startswith(('DEC-','CONST-')) else 'CURRENT_ARCHITECTURE'
  if match:source['system_version']=match['system_version']
  elif source['evidence_id']=='DEC-AUTHORITY':source['system_version']='PRE_S'
  elif source['evidence_id']=='DEC-R128':source['system_version']='S_ACTIVE'
  elif source['evidence_maturity']=='CURRENT_ARCHITECTURE':source['system_version']='S_PLUS_E_ACTIVE'
 dump('self-introspection-manifest.json',dict(status='PASS',snapshot=PARENT,active_source=PROMOTION,method='AST/source checks plus published promotion metadata; existing pure select_route computes historical mechanical facts. Source-bound records never invoke active selectors or construct protected stores.',source_index=source_index,component_manifest_verified_against_frozen_sources=True,decision_records=len(records),mechanical_routes_recomputed=len(records),S_rule='Absent before S; recorded suffix below source threshold proves false on included S_ACTIVE records. Otherwise UNKNOWN.',E_rule='Not active for sampled historical versions. No counterfactual current E outcome is inferred.',private_streams_opened=0,world_executions=0,memory_writes=0))
 print(json.dumps(dict(status='PASS',evidence_items=len(evidence),decision_records=len(records),source_files=len(source_index))))
if __name__=='__main__':main()
