"""Prospective conjunctions; two claim families each receive alpha .025."""
import math
import numpy as np

def sign_p(values):
 w=sum(x>1e-12 for x in values);l=sum(x< -1e-12 for x in values);n=w+l
 return sum(math.comb(n,k) for k in range(w,n+1))/2**n if n else 1.

def compare(target,base,summaries,x,a,seed):
 pairs=[]
 for t,b in zip(target,base):
  assert t['world_id']==b['world_id']
  pairs.append(dict(world_id=t['world_id'],information_advantage_bits=t['information']-b['information'],uncertainty_area_reduction=b['uncertainty_area']-t['uncertainty_area'],repeat_difference=t['repeats']-b['repeats'],zero_information_difference=t['zero_information']-b['zero_information'],useful_contrast_difference=t['useful_contrasts']-b['useful_contrasts'],unique_probes_difference=t['unique_probes']-b['unique_probes'],short_exact_difference=t['short_exact']-b['short_exact'],short_correct_bits_difference=t['short_correct_bits']-b['short_correct_bits']))
 d=[p['information_advantage_bits'] for p in pairs];area=[p['uncertainty_area_reduction'] for p in pairs];bits=np.array([p['short_correct_bits_difference']/36 for p in pairs]);rng=np.random.default_rng(seed);boot=bits[rng.integers(0,len(bits),(100000,len(bits)))].mean(1);t,b=summaries[x],summaries[a]
 return dict(paired_worlds=pairs,median_paired_information_advantage_bits=float(np.median(d)),mean_information_per_probe_advantage=float(np.mean(d))/8,information_wins=sum(v>1e-12 for v in d),information_ties=sum(abs(v)<=1e-12 for v in d),information_losses=sum(v< -1e-12 for v in d),information_sign_p=sign_p(d),area_sign_p=sign_p(area),uncertainty_area_ratio=t['mean_uncertainty_area']/b['mean_uncertainty_area'],repeat_reduction=b['exact_repeats']-t['exact_repeats'],repeat_ratio=t['exact_repeats']/b['exact_repeats'] if b['exact_repeats'] else None,zero_information_reduction=b['zero_information']-t['zero_information'],zero_information_ratio=t['zero_information']/b['zero_information'] if b['zero_information'] else None,short_exact_difference=t['prediction']['exact']-b['prediction']['exact'],short_bit_accuracy_difference=float(bits.mean()),paired_world_bootstrap_bit_difference_lower_97_5=float(np.quantile(boot,.025)),bootstrap_seed=seed,bootstrap_resamples=100000)

def decision(comp,arms,questions,integrity=True):
 def prediction(c):return dict(exact_prediction_count_not_lower=c['short_exact_difference']>=0,bit_accuracy_noninferior_2pp=c['paired_world_bootstrap_bit_difference_lower_97_5']>-.02,integrity=integrity)
 c=comp['B-A'];b=dict(baseline_repeats_at_least24=arms['A']['exact_repeats']>=24,repeats_at_least50pct_lower=c['repeat_ratio'] is not None and c['repeat_ratio']<=.5,repeats_at_least24_lower=c['repeat_reduction']>=24,zero_information_at_least40pct_lower=c['zero_information_ratio'] is not None and c['zero_information_ratio']<=.6,zero_information_at_least24_lower=c['zero_information_reduction']>=24,median_paired_information_at_least1bit=c['median_paired_information_advantage_bits']>=1-1e-12,information_sign_p_below_025=c['information_sign_p']<.025,uncertainty_area_at_least15pct_lower=c['uncertainty_area_ratio']<=.85,area_sign_p_below_025=c['area_sign_p']<.025,**prediction(c))
 c=comp['O-B'];q=questions;ng=q.get('generated_questions',0);rate=q.get('questions_followed_by_informative_target_execution',0)/ng if ng else 0.;bpositive=1-arms['B']['zero_information']/arms['B']['experiments']
 o=dict(mean_information_per_probe_advantage_at_least_eighth_bit=c['mean_information_per_probe_advantage']>=.125-1e-12,median_paired_information_at_least_half_bit=c['median_paired_information_advantage_bits']>=.5-1e-12,information_sign_p_below_025=c['information_sign_p']<.025,zero_information_at_least20pct_lower=c['zero_information_ratio'] is not None and c['zero_information_ratio']<=.8,zero_information_at_least12_lower=c['zero_information_reduction']>=12,uncertainty_area_at_least5pct_lower=c['uncertainty_area_ratio']<=.95,area_sign_p_below_025=c['area_sign_p']<.025,at_least192_questions=ng>=192,question_linked_informative_fraction_at_least75pct=rate>=.75,question_linked_informative_fraction_exceeds_B_positive_fraction_by5pp=rate>=bpositive+.05-1e-12,all_frontier_schemas_valid=q.get('invalid_frontier_schema',0)==0,**prediction(c))
 bs,os=all(b.values()),all(o.values())
 return dict(bookkeeping=dict(supported=bs,result='GROUNDED_INQUIRY_BOOKKEEPING_CONFIRMED' if bs else 'GROUNDED_INQUIRY_BOOKKEEPING_NOT_CONFIRMED',conditions=b),open_frontier=dict(supported=os,result='OPEN_INQUIRY_FRONTIER_SUPPORTED' if os else 'OPEN_INQUIRY_FRONTIER_NOT_SUPPORTED',conditions=o),classification=('BOOKKEEPING_AND_OPEN_FRONTIER_SUPPORTED' if os else 'BOOKKEEPING_CONFIRMED_OPEN_FRONTIER_NOT_SUPPORTED') if bs else ('OPEN_FRONTIER_SUPPORTED_BOOKKEEPING_NOT_CONFIRMED' if os else 'NEITHER_INTERVENTION_CONFIRMED'),integration_candidate='O bundle for separate review' if bs and os else 'B bookkeeping bundle for separate review' if bs else None,no_training=True,no_merge=True,no_automatic_followup=True,question_linked_informative_fraction=rate,B_positive_experiment_fraction=bpositive)
