"""Deterministic final report from frozen measurements and literal gates."""
from common import *
def render(r,handoff,replay,preservation):
 lines=[];d=r['decision'];arms=r['arms'];q=r['question_counts'];comp=r['paired_comparisons']
 def add(s=''):lines.append(s)
 def table(head,rows):
  add('| '+' | '.join(head)+' |');add('| '+' | '.join(['---']*len(head))+' |')
  for row in rows:add('| '+' | '.join(map(str,row))+' |')
  add()
 add('# Horus Inquiry State Confirmatory v0');add();add('**'+d['classification']+'**');add()
 add('All 1,968 scientific responses completed across 48 fresh matched worlds: eight discovery probes and three shared sealed predictions per arm. O adds 384 fresh interpretation calls. The pilot and earlier studies are preserved unchanged. No training, merge or automatic follow-up.');add()
 add('A is generic Active; B adds grounded bookkeeping and the deterministic-reset reminder; O adds a new model interpretation before each choice, reconstructed from the full authenticated ledger. Only the current interpretation enters that step. All interpretations remain unverified. The finite hypothesis evaluator, utility, candidate programs and sealed outcomes are hidden. Known actions and untried actions are explicitly not exhaustive reality.');add()
 add('## Provenance');add();table(['Artifact','Identity'],[(k,'`'+str(v)+'`') for k,v in handoff.items()]);add('Remote publication is verified in the private publication receipt; the containing Git commit identifies this report without a self-referential SHA.');add()
 add('## Matched outcomes');add();table(['Arm','Repeats /384','Zero-info /384','Unique total','Mean information bits','Median final H','Median log2 H','Mean uncertainty area','Useful contrasts','Exact /144','Bit accuracy','Mean rank','Mean regret'],[(a,z['exact_repeats'],z['zero_information'],z['unique_probe_sequences'],round(z['mean_information_bits'],4),z['median_final_H'],round(z['median_final_log2_H'],4),round(z['mean_uncertainty_area'],4),z['useful_controlled_contrasts'],z['prediction']['exact'],round(z['prediction']['bit_accuracy'],5),round(z['mean_selected_rank'],3),round(z['mean_regret_bits'],4)) for a,z in arms.items()])
 table(['Arm','Calls','Prompt tokens','Generated tokens','Inference seconds'],[(a,c['model_calls'],c['prompt_tokens'],c['generation_token_count'],round(c['seconds'],2)) for a,c in r['costs'].items()])
 add('## Learning curves');add();table(['Arm','Probe','Median log2 H','Mean cumulative bits','Repeats','Zero-info','Useful contrasts'],[(a,t,round(z['curves'][str(t)]['median_log2_H'],4),round(z['curves'][str(t)]['mean_cumulative_bits'],4),z['curves'][str(t)]['exact_repeats'],z['curves'][str(t)]['zero_information'],z['curves'][str(t)]['useful_contrasts']) for a,z in arms.items() for t in [1,2,3,4,6,8]])
 add('## Preregistered comparisons');add();table(['Comparison','Median paired bits','Mean bits/probe advantage','Wins/ties/losses','Information sign p','Area ratio','Area sign p','Zero-info ratio','Exact difference','Bit difference','97.5% lower bit bound'],[(n,round(c['median_paired_information_advantage_bits'],4),round(c['mean_information_per_probe_advantage'],4),str(c['information_wins'])+'/'+str(c['information_ties'])+'/'+str(c['information_losses']),c['information_sign_p'],c['uncertainty_area_ratio'],c['area_sign_p'],c['zero_information_ratio'],c['short_exact_difference'],c['short_bit_accuracy_difference'],c['paired_world_bootstrap_bit_difference_lower_97_5']) for n,c in comp.items()])
 for name in ['bookkeeping','open_frontier']:
  g=d[name];add('**'+g['result']+'**. '+('Every required condition passed.' if g['supported'] else 'Failed conditions: '+', '.join(k for k,v in g['conditions'].items() if not v)+'.'));add()
 add('The two claim families use alpha 0.025 each. Each claim requires its complete conjunction of exact paired sign tests, effect thresholds, retention and integrity; no metric can substitute for a failed gate. Bit noninferiority uses 100,000 paired world bootstrap samples and a two-percentage-point margin. Exact prediction count may not decline. Exact accuracy noninferiority is not a powered claim. All 48 paired differences are in results.json.');add()
 add('## O question accounting');add();table(['Measure','Count'],sorted(q.items()));add('Question-linked informative fraction: '+str(d['question_linked_informative_fraction'])+'. B positive-experiment fraction: '+str(d['B_positive_experiment_fraction'])+'. B does not generate questions; this comparison is the preregistered asymmetric behavioral benchmark, not a B question-resolution rate.');add()
 add('A scored question names a model-selected probe and sensor. Resolution requires later executed evidence containing that target trace, not an oracle answer. Prose is an unscored gloss. Repeated keyed questions without new target evidence measure persistence descriptively; they do not diagnose internal fixation. Finite H ambiguity can corroborate a limited uncertainty statement, never certify general open-world impossibility or exhaustive truth.');add()
 add('## Integrity');add();add('All raw responses were frozen and committed before scoring. Exact prompt/ledger reconstruction, authentication, legal-ID paths, sealed query boundaries and byte-identical scoring replay passed. Replay and scoring made zero model calls. The model receives only the current fresh interpretation; prior interpretation text is absent by construction and replay. Complete invalid frontier outputs are retained, never retried for scientific quality.');add();add('Audits: `'+canon(r['audits'])+'`. Replay: `'+canon(replay)+'`. Preservation: `'+canon(preservation)+'`.');add()
 add('## Ten requested answers');add()
 answers=[('Did B replicate the pilot?',d['bookkeeping']['result']+'. The complete confirmatory gate is the governing result.'),('Did bookkeeping prevent active-exploration collapse?',f"A/B repeats: {arms['A']['exact_repeats']}/{arms['B']['exact_repeats']}; zero-information probes: {arms['A']['zero_information']}/{arms['B']['zero_information']}. These describe wasted inquiry in this population, not a universal prevention claim."),('Did the information benefit survive to eight probes?',f"B-A median paired final information advantage: {comp['B-A']['median_paired_information_advantage_bits']:.4f} bits; exact sign p={comp['B-A']['information_sign_p']}. The full curves show early and final behavior."),('Did O generate useful unresolved questions from reality?',f"O generated {q.get('generated_questions',0)} measurement-linked questions, of which {q.get('questions_unobserved_at_generation',0)} concerned traces not yet observed and {q.get('unobserved_questions_later_answered_by_execution',0)} were later answered by executed evidence. This does not certify the associated prose."),('Did those questions lead to more informative experiments?',f"{q.get('questions_followed_by_informative_target_execution',0)} generated questions were immediately followed by an informative execution covering their target. O-B mean information advantage per probe: {comp['O-B']['mean_information_per_probe_advantage']:.4f} bits. Association does not isolate causal influence from the extra inference call."),('Did O avoid treating previous hypotheses as truth?','Previous interpretations were never carried into later steps; all current interpretations were explicitly marked unverified. This verifies the context boundary, not the model’s internal beliefs. Repeated question counts remain a separate fixation diagnostic.'),('Did O correctly retain uncertainty rather than force closure?',f"The explicit unresolved state was used {q.get('unresolved_status_uses',0)} times; {q.get('unresolved_status_with_finite_H_ambiguity',0)} coincided with finite-family ambiguity. This is scoped corroboration only. Neither absence nor presence of finite ambiguity establishes all open-world possibilities."),('Did O improve over B?',d['open_frontier']['result']+'. No conceptual preference overrides that gate.'),('What remains missing for genuinely open-world inquiry?','This still uses fixed sensors, reset dynamics and known interventions. It does not test discovering new instruments, expanding representations, open-ended causal explanations, calibrated impossibility judgments or environmental change. O also uses extra inference, so any benefit is for that bundle.'),('Which piece is justified for integration review?',str(d['integration_candidate'])+'. This is a result for separate integration review; no architecture, policy or parameters were changed.')]
 for i,(question,answer) in enumerate(answers,1):add(f'{i}. **{question}** {answer}');add()
 add('STOP. No training, merge or subsequent study.')
 return '\n'.join(lines)+'\n'
